// Auto-generated pericopes for Ruth (book 8)
// Generated by scripts/generate_pericopes_from_db.js

export const RUTH_PERICOPES = [
  { chapter: 1, verse_start: 1, verse_end: 12, name: "Now Came Pass Days When Judges" },
  { chapter: 1, verse_start: 13, verse_end: 22, name: "Would Ye Tarry Them Till Grown" },
  { chapter: 2, verse_start: 1, verse_end: 12, name: "Naomi Had Kinsman Husbands Mighty Man" },
  { chapter: 2, verse_start: 13, verse_end: 23, name: "Then Said Let Me Find Favour" },
  { chapter: 3, verse_start: 1, verse_end: 12, name: "Then Naomi Mother Law Said Unto" },
  { chapter: 3, verse_start: 13, verse_end: 18, name: "Tarry Night Morning If Will Perform" },
  { chapter: 4, verse_start: 1, verse_end: 12, name: "Then Went Boaz Up Gate Sat" },
  { chapter: 4, verse_start: 13, verse_end: 22, name: "So Boaz Took Ruth Wife When" }
];
