// Auto-generated pericopes for Ezra (book 15)
// Generated by scripts/generate_pericopes_from_db.js

export const EZRA_PERICOPES = [
  { chapter: 1, verse_start: 1, verse_end: 11, name: "Now First Year Cyrus King Persia" },
  { chapter: 2, verse_start: 1, verse_end: 12, name: "Now Children Province Went Up Out" },
  { chapter: 2, verse_start: 13, verse_end: 24, name: "Children Adonikam Six Hundred Sixty Six" },
  { chapter: 2, verse_start: 25, verse_end: 36, name: "Children Kirjatharim Chephirah Beeroth Seven Hundred" },
  { chapter: 2, verse_start: 37, verse_end: 48, name: "Children Immer Thousand Fifty Two" },
  { chapter: 2, verse_start: 49, verse_end: 60, name: "Children Uzza Children Paseah Children Besai" },
  { chapter: 2, verse_start: 61, verse_end: 70, name: "Children Priests Children Habaiah Children Koz" },
  { chapter: 3, verse_start: 1, verse_end: 13, name: "When Seventh Month Come Children Israel" },
  { chapter: 4, verse_start: 1, verse_end: 12, name: "Now When Adversaries Judah Benjamin Heard" },
  { chapter: 4, verse_start: 13, verse_end: 24, name: "Known Now Unto King If City" },
  { chapter: 5, verse_start: 1, verse_end: 17, name: "Then Prophets Haggai Prophet Zechariah Son" },
  { chapter: 6, verse_start: 1, verse_end: 12, name: "Then Darius King Made Decree Search" },
  { chapter: 6, verse_start: 13, verse_end: 22, name: "Then Tatnai Governor Side River Shetharboznai" },
  { chapter: 7, verse_start: 1, verse_end: 12, name: "Now After Things Reign Artaxerxes King" },
  { chapter: 7, verse_start: 13, verse_end: 28, name: "Make Decree All People Israel Priests" },
  { chapter: 8, verse_start: 1, verse_end: 12, name: "Now Chief Fathers Genealogy Them Went" },
  { chapter: 8, verse_start: 13, verse_end: 24, name: "Last Sons Adonikam Whose Names Eliphelet" },
  { chapter: 8, verse_start: 25, verse_end: 36, name: "Weighed Unto Them Silver Gold Vessels" },
  { chapter: 9, verse_start: 1, verse_end: 15, name: "Now When Things Done Princes Came" },
  { chapter: 10, verse_start: 1, verse_end: 12, name: "Now When Ezra Had Prayed When" },
  { chapter: 10, verse_start: 13, verse_end: 24, name: "But People Many Time Much Rain" },
  { chapter: 10, verse_start: 25, verse_end: 36, name: "Moreover Israel Sons Parosh Ramiah Jeziah" },
  { chapter: 10, verse_start: 37, verse_end: 44, name: "Mattaniah Mattenai Jaasau" }
];
