// Auto-generated pericopes for Esther (book 17)
// Generated by scripts/generate_pericopes_from_db.js

export const ESTHER_PERICOPES = [
  { chapter: 1, verse_start: 1, verse_end: 12, name: "Now Came Pass Days Ahasuerus Ahasuerus" },
  { chapter: 1, verse_start: 13, verse_end: 22, name: "Then King Said Wise Men Knew" },
  { chapter: 2, verse_start: 1, verse_end: 12, name: "After Things When Wrath King Ahasuerus" },
  { chapter: 2, verse_start: 13, verse_end: 23, name: "Then Thus Came Every Maiden Unto" },
  { chapter: 3, verse_start: 1, verse_end: 15, name: "After Things Did King Ahasuerus Promote" },
  { chapter: 4, verse_start: 1, verse_end: 17, name: "When Mordecai Perceived All Done Mordecai" },
  { chapter: 5, verse_start: 1, verse_end: 14, name: "Now Came Pass Third Day Esther" },
  { chapter: 6, verse_start: 1, verse_end: 14, name: "Night Could Not King Sleep Commanded" },
  { chapter: 7, verse_start: 1, verse_end: 10, name: "So King Haman Came Banquet Esther" },
  { chapter: 8, verse_start: 1, verse_end: 17, name: "Day Did King Ahasuerus Give House" },
  { chapter: 9, verse_start: 1, verse_end: 12, name: "Now Twelfth Month Month Adar Thirteenth" },
  { chapter: 9, verse_start: 13, verse_end: 24, name: "Then Said Esther If Please King" },
  { chapter: 9, verse_start: 25, verse_end: 32, name: "But When Esther Came Before King" },
  { chapter: 10, verse_start: 1, verse_end: 3, name: "King Ahasuerus Laid Tribute Upon Land" }
];
