// Auto-generated pericopes for Ecclesiastes (book 21)
// Generated by scripts/generate_pericopes_from_db.js

export const ECCLESIASTES_PERICOPES = [
  { chapter: 1, verse_start: 1, verse_end: 12, name: "Words Preacher Son David King Jerusalem" },
  { chapter: 1, verse_start: 13, verse_end: 18, name: "Gave My Heart Seek Search Out" },
  { chapter: 2, verse_start: 1, verse_end: 12, name: "Said Mine Heart Go Now Will" },
  { chapter: 2, verse_start: 13, verse_end: 26, name: "Then Saw Wisdom Excelleth Folly Far" },
  { chapter: 3, verse_start: 1, verse_end: 12, name: "Every Thing There Season Time Every" },
  { chapter: 3, verse_start: 13, verse_end: 22, name: "Also Every Man Should Eat Drink" },
  { chapter: 4, verse_start: 1, verse_end: 16, name: "So Returned Considered All Oppressions Done" },
  { chapter: 5, verse_start: 1, verse_end: 12, name: "Keep Thy Foot When Thou Goest" },
  { chapter: 5, verse_start: 13, verse_end: 20, name: "There Sore Evil Have Seen Under" },
  { chapter: 6, verse_start: 1, verse_end: 12, name: "There An Evil Have Seen Under" },
  { chapter: 7, verse_start: 1, verse_end: 12, name: "Good Name Better Than Precious Ointment" },
  { chapter: 7, verse_start: 13, verse_end: 29, name: "Consider Work God Can Make Straight" },
  { chapter: 8, verse_start: 1, verse_end: 17, name: "Wise Man Knoweth Interpretation Thing Mans" },
  { chapter: 9, verse_start: 1, verse_end: 12, name: "All Considered My Heart Even Declare" },
  { chapter: 9, verse_start: 13, verse_end: 18, name: "Wisdom Have Seen Also Under Sun" },
  { chapter: 10, verse_start: 1, verse_end: 12, name: "Dead Flies Cause Ointment Apothecary Send" },
  { chapter: 10, verse_start: 13, verse_end: 20, name: "Beginning Words Mouth Foolishness End Talk" },
  { chapter: 11, verse_start: 1, verse_end: 10, name: "Cast Thy Bread Upon Waters Thou" },
  { chapter: 12, verse_start: 1, verse_end: 14, name: "Remember Now Thy Creator Days Thy" }
];
