// Auto-generated pericopes for Song of Solomon (book 22)
// Generated by scripts/generate_pericopes_from_db.js

export const SONGOFSOL_PERICOPES = [
  { chapter: 1, verse_start: 1, verse_end: 17, name: "Song Songs Solomons" },
  { chapter: 2, verse_start: 1, verse_end: 17, name: "Am Rose Sharon Lily Valleys" },
  { chapter: 3, verse_start: 1, verse_end: 11, name: "Night My Bed Sought Him My" },
  { chapter: 4, verse_start: 1, verse_end: 16, name: "Behold Thou Art Fair My Love" },
  { chapter: 5, verse_start: 1, verse_end: 16, name: "Am Come Into My Garden My" },
  { chapter: 6, verse_start: 1, verse_end: 13, name: "Whither Thy Beloved Gone O Thou" },
  { chapter: 7, verse_start: 1, verse_end: 13, name: "How Beautiful Thy Feet Shoes O" },
  { chapter: 8, verse_start: 1, verse_end: 14, name: "O Thou Wert My Brother Sucked" }
];
