// Auto-generated pericopes for Lamentations (book 25)
// Generated by scripts/generate_pericopes_from_db.js

export const LAMENTATIONS_PERICOPES = [
  { chapter: 1, verse_start: 1, verse_end: 12, name: "How Doth City Sit Solitary Full" },
  { chapter: 1, verse_start: 13, verse_end: 22, name: "Above Hath Sent Fire Into My" },
  { chapter: 2, verse_start: 1, verse_end: 12, name: "How Hath Lord Covered Daughter Zion" },
  { chapter: 2, verse_start: 13, verse_end: 22, name: "What Thing Take Witness Thee What" },
  { chapter: 3, verse_start: 1, verse_end: 12, name: "Am Man Hath Seen Affliction Rod" },
  { chapter: 3, verse_start: 13, verse_end: 24, name: "Hath Caused Arrows Quiver Enter Into" },
  { chapter: 3, verse_start: 25, verse_end: 36, name: "LORD Good Unto Them Wait Him" },
  { chapter: 3, verse_start: 37, verse_end: 48, name: "Saith Cometh Pass When Lord Commandeth" },
  { chapter: 3, verse_start: 49, verse_end: 60, name: "Mine Eye Trickleth Down Ceaseth Not" },
  { chapter: 3, verse_start: 61, verse_end: 66, name: "Thou Hast Heard Reproach O LORD" },
  { chapter: 4, verse_start: 1, verse_end: 12, name: "How Gold Become Dim How Most" },
  { chapter: 4, verse_start: 13, verse_end: 22, name: "Sins Prophets Iniquities Priests Have Shed" },
  { chapter: 5, verse_start: 1, verse_end: 12, name: "Remember O LORD What Come Upon" },
  { chapter: 5, verse_start: 13, verse_end: 22, name: "Took Young Men Grind Children Fell" }
];
