// Auto-generated pericopes for Hosea (book 28)
// Generated by scripts/generate_pericopes_from_db.js

export const HOSEA_PERICOPES = [
  { chapter: 1, verse_start: 1, verse_end: 11, name: "Word LORD Came Unto Hosea Son" },
  { chapter: 2, verse_start: 1, verse_end: 12, name: "Say Ye Unto Brethren Ammi Sisters" },
  { chapter: 2, verse_start: 13, verse_end: 23, name: "Will Visit Upon Days Baalim Wherein" },
  { chapter: 3, verse_start: 1, verse_end: 5, name: "Then Said LORD Unto Me Go" },
  { chapter: 4, verse_start: 1, verse_end: 12, name: "Hear Word LORD Ye Children Israel" },
  { chapter: 4, verse_start: 13, verse_end: 19, name: "Sacrifice Upon Tops Mountains Burn Incense" },
  { chapter: 5, verse_start: 1, verse_end: 15, name: "Hear Ye O Priests Hearken Ye" },
  { chapter: 6, verse_start: 1, verse_end: 11, name: "Come Let Us Return Unto LORD" },
  { chapter: 7, verse_start: 1, verse_end: 16, name: "When Would Have Healed Israel Then" },
  { chapter: 8, verse_start: 1, verse_end: 14, name: "Set Trumpet Thy Mouth Come An" },
  { chapter: 9, verse_start: 1, verse_end: 17, name: "Rejoice Not O Israel Joy Other" },
  { chapter: 10, verse_start: 1, verse_end: 15, name: "Israel An Empty Vine Bringeth Forth" },
  { chapter: 11, verse_start: 1, verse_end: 12, name: "When Israel Child Then Loved Him" },
  { chapter: 12, verse_start: 1, verse_end: 14, name: "Ephraim Feedeth Wind Followeth After East" },
  { chapter: 13, verse_start: 1, verse_end: 16, name: "When Ephraim Spake Trembling Exalted Himself" },
  { chapter: 14, verse_start: 1, verse_end: 9, name: "O Israel Return Unto LORD Thy" }
];
