// Auto-generated pericopes for Joel (book 29)
// Generated by scripts/generate_pericopes_from_db.js

export const JOEL_PERICOPES = [
  { chapter: 1, verse_start: 1, verse_end: 12, name: "Word LORD Came Joel Son Pethuel" },
  { chapter: 1, verse_start: 13, verse_end: 20, name: "Gird Yourselves Lament Ye Priests Howl" },
  { chapter: 2, verse_start: 1, verse_end: 12, name: "Blow Ye Trumpet Zion Sound An" },
  { chapter: 2, verse_start: 13, verse_end: 24, name: "Rend Heart Not Garments Turn Unto" },
  { chapter: 2, verse_start: 25, verse_end: 32, name: "Will Restore Years Locust Hath Eaten" },
  { chapter: 3, verse_start: 1, verse_end: 12, name: "Behold Days Time When Bring Again" },
  { chapter: 3, verse_start: 13, verse_end: 21, name: "Put Ye Sickle Harvest Ripe Come" }
];
