// Auto-generated pericopes for Amos (book 30)
// Generated by scripts/generate_pericopes_from_db.js

export const AMOS_PERICOPES = [
  { chapter: 1, verse_start: 1, verse_end: 15, name: "Words Amos Among Herdmen Tekoa Saw" },
  { chapter: 2, verse_start: 1, verse_end: 16, name: "Thus Saith LORD Three Transgressions Moab" },
  { chapter: 3, verse_start: 1, verse_end: 15, name: "Hear Word LORD Hath Spoken Against" },
  { chapter: 4, verse_start: 1, verse_end: 13, name: "Hear Word Ye Kine Bashan Mountain" },
  { chapter: 5, verse_start: 1, verse_end: 12, name: "Hear Ye Word Take Up Against" },
  { chapter: 5, verse_start: 13, verse_end: 27, name: "Therefore Prudent Keep Silence Time An" },
  { chapter: 6, verse_start: 1, verse_end: 14, name: "Woe Them At Ease Zion Trust" },
  { chapter: 7, verse_start: 1, verse_end: 17, name: "Thus Hath Lord GOD Shewed Unto" },
  { chapter: 8, verse_start: 1, verse_end: 14, name: "Thus Hath Lord GOD Shewed Unto" },
  { chapter: 9, verse_start: 1, verse_end: 15, name: "Saw Lord Standing Upon Altar Said" }
];
