// Auto-generated pericopes for Obadiah (book 31)
// Generated by scripts/generate_pericopes_from_db.js

export const OBADIAH_PERICOPES = [
  { chapter: 1, verse_start: 1, verse_end: 12, name: "Vision Obadiah Thus Saith Lord GOD" },
  { chapter: 1, verse_start: 13, verse_end: 21, name: "Thou Shouldest Not Have Entered Into" }
];
