// Auto-generated pericopes for Jonah (book 32)
// Generated by scripts/generate_pericopes_from_db.js

export const JONAH_PERICOPES = [
  { chapter: 1, verse_start: 1, verse_end: 17, name: "Now Word LORD Came Unto Jonah" },
  { chapter: 2, verse_start: 1, verse_end: 10, name: "Then Jonah Prayed Unto LORD God" },
  { chapter: 3, verse_start: 1, verse_end: 10, name: "Word LORD Came Unto Jonah Second" },
  { chapter: 4, verse_start: 1, verse_end: 11, name: "But Displeased Jonah Exceedingly Very Angry" }
];
