// Auto-generated pericopes for Micah (book 33)
// Generated by scripts/generate_pericopes_from_db.js

export const MICAH_PERICOPES = [
  { chapter: 1, verse_start: 1, verse_end: 16, name: "Word LORD Came Micah Morasthite Days" },
  { chapter: 2, verse_start: 1, verse_end: 13, name: "Woe Them Devise Iniquity Work Evil" },
  { chapter: 3, verse_start: 1, verse_end: 12, name: "Said Hear Pray O Heads Jacob" },
  { chapter: 4, verse_start: 1, verse_end: 13, name: "But Last Days Come Pass Mountain" },
  { chapter: 5, verse_start: 1, verse_end: 15, name: "Now Gather Thyself Troops O Daughter" },
  { chapter: 6, verse_start: 1, verse_end: 16, name: "Hear Ye Now What LORD Saith" },
  { chapter: 7, verse_start: 1, verse_end: 12, name: "Woe Me Am When Have Gathered" },
  { chapter: 7, verse_start: 13, verse_end: 20, name: "Notwithstanding Land Desolate Because Them Dwell" }
];
