// Auto-generated pericopes for Nahum (book 34)
// Generated by scripts/generate_pericopes_from_db.js

export const NAHUM_PERICOPES = [
  { chapter: 1, verse_start: 1, verse_end: 15, name: "Burden Nineveh Book Vision Nahum Elkoshite" },
  { chapter: 2, verse_start: 1, verse_end: 13, name: "Dasheth Pieces Come Up Before Thy" },
  { chapter: 3, verse_start: 1, verse_end: 12, name: "Woe Bloody City All Full Lies" },
  { chapter: 3, verse_start: 13, verse_end: 19, name: "Behold Thy People Midst Thee Women" }
];
