// Auto-generated pericopes for Habakkuk (book 35)
// Generated by scripts/generate_pericopes_from_db.js

export const HABAKKUK_PERICOPES = [
  { chapter: 1, verse_start: 1, verse_end: 17, name: "Burden Habakkuk Prophet Did See" },
  { chapter: 2, verse_start: 1, verse_end: 12, name: "Will Stand Upon My Watch Set" },
  { chapter: 2, verse_start: 13, verse_end: 20, name: "Behold Not LORD Hosts People Labour" },
  { chapter: 3, verse_start: 1, verse_end: 12, name: "Prayer Habakkuk Prophet Upon Shigionoth" },
  { chapter: 3, verse_start: 13, verse_end: 19, name: "Thou Wentest Forth Salvation Thy People" }
];
