// Auto-generated pericopes for Zephaniah (book 36)
// Generated by scripts/generate_pericopes_from_db.js

export const ZEPHANIAH_PERICOPES = [
  { chapter: 1, verse_start: 1, verse_end: 12, name: "Word LORD Came Unto Zephaniah Son" },
  { chapter: 1, verse_start: 13, verse_end: 18, name: "Therefore Goods Become Booty Houses Desolation" },
  { chapter: 2, verse_start: 1, verse_end: 15, name: "Gather Yourselves Together Yea Gather Together" },
  { chapter: 3, verse_start: 1, verse_end: 12, name: "Woe Filthy Polluted Oppressing City" },
  { chapter: 3, verse_start: 13, verse_end: 20, name: "Remnant Israel Not Do Iniquity Nor" }
];
