// Auto-generated pericopes for Haggai (book 37)
// Generated by scripts/generate_pericopes_from_db.js

export const HAGGAI_PERICOPES = [
  { chapter: 1, verse_start: 1, verse_end: 15, name: "Second Year Darius King Sixth Month" },
  { chapter: 2, verse_start: 1, verse_end: 12, name: "Seventh Month One Twentieth Day Month" },
  { chapter: 2, verse_start: 13, verse_end: 23, name: "Then Said Haggai If One Unclean" }
];
