// Auto-generated pericopes for Zechariah (book 38)
// Generated by scripts/generate_pericopes_from_db.js

export const ZECHARIAH_PERICOPES = [
  { chapter: 1, verse_start: 1, verse_end: 12, name: "Eighth Month Second Year Darius Came" },
  { chapter: 1, verse_start: 13, verse_end: 21, name: "LORD Answered Angel Talked Me Good" },
  { chapter: 2, verse_start: 1, verse_end: 13, name: "Lifted Up Mine Eyes Again Looked" },
  { chapter: 3, verse_start: 1, verse_end: 10, name: "Shewed Me Joshua High Priest Standing" },
  { chapter: 4, verse_start: 1, verse_end: 14, name: "Angel Talked Me Came Again Waked" },
  { chapter: 5, verse_start: 1, verse_end: 11, name: "Then Turned Lifted Up Mine Eyes" },
  { chapter: 6, verse_start: 1, verse_end: 15, name: "Turned Lifted Up Mine Eyes Looked" },
  { chapter: 7, verse_start: 1, verse_end: 14, name: "Came Pass Fourth Year King Darius" },
  { chapter: 8, verse_start: 1, verse_end: 12, name: "Again Word LORD Hosts Came Me" },
  { chapter: 8, verse_start: 13, verse_end: 23, name: "Come Pass Ye Curse Among Heathen" },
  { chapter: 9, verse_start: 1, verse_end: 17, name: "Burden Word LORD Land Hadrach Damascus" },
  { chapter: 10, verse_start: 1, verse_end: 12, name: "Ask Ye LORD Rain Time Latter" },
  { chapter: 11, verse_start: 1, verse_end: 17, name: "Open Thy Doors O Lebanon Fire" },
  { chapter: 12, verse_start: 1, verse_end: 14, name: "Burden Word LORD Israel Saith LORD" },
  { chapter: 13, verse_start: 1, verse_end: 9, name: "Day There Fountain Opened House David" },
  { chapter: 14, verse_start: 1, verse_end: 12, name: "Behold Day LORD Cometh Thy Spoil" },
  { chapter: 14, verse_start: 13, verse_end: 21, name: "Come Pass Day Great Tumult LORD" }
];
