// Auto-generated pericopes for Malachi (book 39)
// Generated by scripts/generate_pericopes_from_db.js

export const MALACHI_PERICOPES = [
  { chapter: 1, verse_start: 1, verse_end: 14, name: "Burden Word LORD Israel Malachi" },
  { chapter: 2, verse_start: 1, verse_end: 17, name: "Now O Ye Priests Commandment" },
  { chapter: 3, verse_start: 1, verse_end: 12, name: "Behold Will Send My Messenger Prepare" },
  { chapter: 3, verse_start: 13, verse_end: 18, name: "Words Have Been Stout Against Me" },
  { chapter: 4, verse_start: 1, verse_end: 6, name: "Behold Day Cometh Burn An Oven" }
];
