// Auto-generated pericopes for 2 Corinthians (book 47)
// Generated by scripts/generate_pericopes_from_db.js

export const CORINTHIANS2_PERICOPES = [
  { chapter: 1, verse_start: 1, verse_end: 12, name: "Paul An Apostle Jesus Christ Will" },
  { chapter: 1, verse_start: 13, verse_end: 24, name: "Write None Other Things Unto Than" },
  { chapter: 2, verse_start: 1, verse_end: 17, name: "But Determined Myself Would Not Come" },
  { chapter: 3, verse_start: 1, verse_end: 12, name: "Do Begin Again Commend Ourselves Or" },
  { chapter: 3, verse_start: 13, verse_end: 18, name: "Not Moses Put Vail Over Face" },
  { chapter: 4, verse_start: 1, verse_end: 12, name: "Therefore Seeing Have Ministry Have Received" },
  { chapter: 4, verse_start: 13, verse_end: 18, name: "Having Same Spirit Faith According Written" },
  { chapter: 5, verse_start: 1, verse_end: 12, name: "Know If Earthly House Tabernacle Dissolved" },
  { chapter: 5, verse_start: 13, verse_end: 21, name: "Whether Beside Ourselves God Or Whether" },
  { chapter: 6, verse_start: 1, verse_end: 12, name: "Then Workers Together Him Beseech Also" },
  { chapter: 6, verse_start: 13, verse_end: 18, name: "Now Recompence Same Speak Unto My" },
  { chapter: 7, verse_start: 1, verse_end: 16, name: "Having Therefore Promises Dearly Beloved Let" },
  { chapter: 8, verse_start: 1, verse_end: 12, name: "Moreover Brethren Do Wit Grace God" },
  { chapter: 8, verse_start: 13, verse_end: 24, name: "Mean Not Other Men Eased Ye" },
  { chapter: 9, verse_start: 1, verse_end: 15, name: "Touching Ministering Saints Superfluous Me Write" },
  { chapter: 10, verse_start: 1, verse_end: 12, name: "Now Paul Myself Beseech Meekness Gentleness" },
  { chapter: 10, verse_start: 13, verse_end: 18, name: "But Will Not Boast Things Without" },
  { chapter: 11, verse_start: 1, verse_end: 12, name: "Would God Ye Could Bear Me" },
  { chapter: 11, verse_start: 13, verse_end: 24, name: "Such False Apostles Deceitful Workers Transforming" },
  { chapter: 11, verse_start: 25, verse_end: 33, name: "Thrice Beaten Rods Once Stoned Thrice" },
  { chapter: 12, verse_start: 1, verse_end: 12, name: "Not Expedient Me Doubtless Glory Will" },
  { chapter: 12, verse_start: 13, verse_end: 21, name: "What Wherein Ye Inferior Other Churches" },
  { chapter: 13, verse_start: 1, verse_end: 14, name: "Third Time Am Coming Mouth Two" }
];
