// Auto-generated pericopes for Galatians (book 48)
// Generated by scripts/generate_pericopes_from_db.js

export const GALATIANS_PERICOPES = [
  { chapter: 1, verse_start: 1, verse_end: 12, name: "Paul An Apostle Not Men Neither" },
  { chapter: 1, verse_start: 13, verse_end: 24, name: "Ye Have Heard My Conversation Time" },
  { chapter: 2, verse_start: 1, verse_end: 12, name: "Then Fourteen Years After Went Up" },
  { chapter: 2, verse_start: 13, verse_end: 21, name: "Other Jews Dissembled Likewise Him Insomuch" },
  { chapter: 3, verse_start: 1, verse_end: 12, name: "O Foolish Galatians Hath Bewitched Ye" },
  { chapter: 3, verse_start: 13, verse_end: 29, name: "Christ Hath Redeemed Us Curse Law" },
  { chapter: 4, verse_start: 1, verse_end: 12, name: "Now Say Heir Long Child Differeth" },
  { chapter: 4, verse_start: 13, verse_end: 24, name: "Ye Know How Through Infirmity Flesh" },
  { chapter: 4, verse_start: 25, verse_end: 31, name: "Agar Mount Sinai Arabia Answereth Jerusalem" },
  { chapter: 5, verse_start: 1, verse_end: 12, name: "Stand Fast Therefore Liberty Wherewith Christ" },
  { chapter: 5, verse_start: 13, verse_end: 26, name: "Brethren Ye Have Been Called Unto" },
  { chapter: 6, verse_start: 1, verse_end: 12, name: "Brethren If Man Overtaken Fault Ye" },
  { chapter: 6, verse_start: 13, verse_end: 18, name: "Neither Themselves Circumcised Keep Law But" }
];
