// Auto-generated pericopes for Ephesians (book 49)
// Generated by scripts/generate_pericopes_from_db.js

export const EPHESIANS_PERICOPES = [
  { chapter: 1, verse_start: 1, verse_end: 12, name: "Paul An Apostle Jesus Christ Will" },
  { chapter: 1, verse_start: 13, verse_end: 23, name: "Ye Also Trusted After Ye Heard" },
  { chapter: 2, verse_start: 1, verse_end: 12, name: "Hath Quickened Dead Trespasses Sins" },
  { chapter: 2, verse_start: 13, verse_end: 22, name: "But Now Christ Jesus Ye Sometimes" },
  { chapter: 3, verse_start: 1, verse_end: 12, name: "Cause Paul Prisoner Jesus Christ Gentiles" },
  { chapter: 3, verse_start: 13, verse_end: 21, name: "Wherefore Desire Ye Faint Not At" },
  { chapter: 4, verse_start: 1, verse_end: 12, name: "Therefore Prisoner Lord Beseech Ye Walk" },
  { chapter: 4, verse_start: 13, verse_end: 24, name: "Till All Come Unity Faith Knowledge" },
  { chapter: 4, verse_start: 25, verse_end: 32, name: "Wherefore Putting Away Lying Speak Every" },
  { chapter: 5, verse_start: 1, verse_end: 12, name: "Ye Therefore Followers God Dear Children" },
  { chapter: 5, verse_start: 13, verse_end: 24, name: "But All Things Reproved Made Manifest" },
  { chapter: 5, verse_start: 25, verse_end: 33, name: "Husbands Love Wives Even Christ Also" },
  { chapter: 6, verse_start: 1, verse_end: 12, name: "Children Obey Parents Lord Right" },
  { chapter: 6, verse_start: 13, verse_end: 24, name: "Wherefore Take Unto Whole Armour God" }
];
