// Auto-generated pericopes for Philippians (book 50)
// Generated by scripts/generate_pericopes_from_db.js

export const PHILIPPIANS_PERICOPES = [
  { chapter: 1, verse_start: 1, verse_end: 12, name: "Paul Timotheus Servants Jesus Christ All" },
  { chapter: 1, verse_start: 13, verse_end: 24, name: "So My Bonds Christ Manifest All" },
  { chapter: 1, verse_start: 25, verse_end: 30, name: "Having Confidence Know Abide Continue All" },
  { chapter: 2, verse_start: 1, verse_end: 12, name: "If There Therefore Any Consolation Christ" },
  { chapter: 2, verse_start: 13, verse_end: 24, name: "God Worketh Both Will Do Good" },
  { chapter: 2, verse_start: 25, verse_end: 30, name: "Yet Supposed Necessary Send Epaphroditus My" },
  { chapter: 3, verse_start: 1, verse_end: 12, name: "Finally My Brethren Rejoice Lord Write" },
  { chapter: 3, verse_start: 13, verse_end: 21, name: "Brethren Count Not Myself Have Apprehended" },
  { chapter: 4, verse_start: 1, verse_end: 12, name: "Therefore My Brethren Dearly Beloved Longed" },
  { chapter: 4, verse_start: 13, verse_end: 23, name: "Can Do All Things Through Christ" }
];
