// Auto-generated pericopes for Colossians (book 51)
// Generated by scripts/generate_pericopes_from_db.js

export const COLOSSIANS_PERICOPES = [
  { chapter: 1, verse_start: 1, verse_end: 12, name: "Paul An Apostle Jesus Christ Will" },
  { chapter: 1, verse_start: 13, verse_end: 29, name: "Hath Delivered Us Power Darkness Hath" },
  { chapter: 2, verse_start: 1, verse_end: 12, name: "Would Ye Knew What Great Conflict" },
  { chapter: 2, verse_start: 13, verse_end: 23, name: "Being Dead Sins Uncircumcision Flesh Hath" },
  { chapter: 3, verse_start: 1, verse_end: 12, name: "If Ye Then Risen Christ Seek" },
  { chapter: 3, verse_start: 13, verse_end: 25, name: "Forbearing One Another Forgiving One Another" },
  { chapter: 4, verse_start: 1, verse_end: 12, name: "Masters Give Unto Servants Just Equal" },
  { chapter: 4, verse_start: 13, verse_end: 18, name: "Bear Him Record Hath Great Zeal" }
];
