// Auto-generated pericopes for 1 Thessalonians (book 52)
// Generated by scripts/generate_pericopes_from_db.js

export const THESSALONIANS1_PERICOPES = [
  { chapter: 1, verse_start: 1, verse_end: 10, name: "Paul Silvanus Timotheus Unto Church Thessalonians" },
  { chapter: 2, verse_start: 1, verse_end: 12, name: "Yourselves Brethren Know Entrance Unto Not" },
  { chapter: 2, verse_start: 13, verse_end: 20, name: "Cause Also Thank God Without Ceasing" },
  { chapter: 3, verse_start: 1, verse_end: 13, name: "Wherefore When Could No Longer Forbear" },
  { chapter: 4, verse_start: 1, verse_end: 12, name: "Furthermore Then Beseech Brethren Exhort Lord" },
  { chapter: 4, verse_start: 13, verse_end: 18, name: "But Would Not Have Ignorant Brethren" },
  { chapter: 5, verse_start: 1, verse_end: 12, name: "But Times Seasons Brethren Ye Have" },
  { chapter: 5, verse_start: 13, verse_end: 28, name: "Esteem Them Very Highly Love Works" }
];
