// Auto-generated pericopes for 2 Thessalonians (book 53)
// Generated by scripts/generate_pericopes_from_db.js

export const THESSALONIANS2_PERICOPES = [
  { chapter: 1, verse_start: 1, verse_end: 12, name: "Paul Silvanus Timotheus Unto Church Thessalonians" },
  { chapter: 2, verse_start: 1, verse_end: 17, name: "Now Beseech Brethren Coming Lord Jesus" },
  { chapter: 3, verse_start: 1, verse_end: 12, name: "Finally Brethren Pray Us Word Lord" },
  { chapter: 3, verse_start: 13, verse_end: 18, name: "But Ye Brethren Not Weary Well" }
];
