// Auto-generated pericopes for 1 Timothy (book 54)
// Generated by scripts/generate_pericopes_from_db.js

export const TIMOTHY1_PERICOPES = [
  { chapter: 1, verse_start: 1, verse_end: 12, name: "Paul An Apostle Jesus Christ Commandment" },
  { chapter: 1, verse_start: 13, verse_end: 20, name: "Before Blasphemer Persecutor Injurious But Obtained" },
  { chapter: 2, verse_start: 1, verse_end: 15, name: "Exhort Therefore First All Supplications Prayers" },
  { chapter: 3, verse_start: 1, verse_end: 16, name: "True Saying If Man Desire Office" },
  { chapter: 4, verse_start: 1, verse_end: 16, name: "Now Spirit Speaketh Expressly Latter Times" },
  { chapter: 5, verse_start: 1, verse_end: 12, name: "Rebuke Not An Elder But Intreat" },
  { chapter: 5, verse_start: 13, verse_end: 25, name: "Withal Learn Idle Wandering About House" },
  { chapter: 6, verse_start: 1, verse_end: 12, name: "Let Many Servants Under Yoke Count" },
  { chapter: 6, verse_start: 13, verse_end: 21, name: "Give Thee Charge Sight God Quickeneth" }
];
