// Auto-generated pericopes for 2 Timothy (book 55)
// Generated by scripts/generate_pericopes_from_db.js

export const TIMOTHY2_PERICOPES = [
  { chapter: 1, verse_start: 1, verse_end: 12, name: "Paul An Apostle Jesus Christ Will" },
  { chapter: 1, verse_start: 13, verse_end: 18, name: "Hold Fast Form Sound Words Thou" },
  { chapter: 2, verse_start: 1, verse_end: 12, name: "Thou Therefore My Son Strong Grace" },
  { chapter: 2, verse_start: 13, verse_end: 26, name: "If Believe Not Yet Abideth Faithful" },
  { chapter: 3, verse_start: 1, verse_end: 17, name: "Know Also Last Days Perilous Times" },
  { chapter: 4, verse_start: 1, verse_end: 12, name: "Charge Thee Therefore Before God Lord" },
  { chapter: 4, verse_start: 13, verse_end: 22, name: "Cloke Left At Troas Carpus When" }
];
