// Auto-generated pericopes for Titus (book 56)
// Generated by scripts/generate_pericopes_from_db.js

export const TITUS_PERICOPES = [
  { chapter: 1, verse_start: 1, verse_end: 16, name: "Paul Servant God An Apostle Jesus" },
  { chapter: 2, verse_start: 1, verse_end: 15, name: "But Speak Thou Things Become Sound" },
  { chapter: 3, verse_start: 1, verse_end: 15, name: "Put Them Mind Subject Principalities Powers" }
];
