// Auto-generated pericopes for Philemon (book 57)
// Generated by scripts/generate_pericopes_from_db.js

export const PHILEMON_PERICOPES = [
  { chapter: 1, verse_start: 1, verse_end: 12, name: "Paul Prisoner Jesus Christ Timothy Brother" },
  { chapter: 1, verse_start: 13, verse_end: 25, name: "Would Have Retained Me Thy Stead" }
];
