// Auto-generated pericopes for Hebrews (book 58)
// Generated by scripts/generate_pericopes_from_db.js

export const HEBREWS_PERICOPES = [
  { chapter: 1, verse_start: 1, verse_end: 14, name: "God At Sundry Times Divers Manners" },
  { chapter: 2, verse_start: 1, verse_end: 12, name: "Therefore Ought Give More Earnest Heed" },
  { chapter: 2, verse_start: 13, verse_end: 18, name: "Again Will Put My Trust Him" },
  { chapter: 3, verse_start: 1, verse_end: 12, name: "Wherefore Holy Brethren Partakers Heavenly Calling" },
  { chapter: 3, verse_start: 13, verse_end: 19, name: "But Exhort One Another Daily While" },
  { chapter: 4, verse_start: 1, verse_end: 16, name: "Let Us Therefore Fear Lest Promise" },
  { chapter: 5, verse_start: 1, verse_end: 14, name: "Every High Priest Taken Among Men" },
  { chapter: 6, verse_start: 1, verse_end: 12, name: "Therefore Leaving Principles Doctrine Christ Let" },
  { chapter: 6, verse_start: 13, verse_end: 20, name: "When God Made Promise Abraham Because" },
  { chapter: 7, verse_start: 1, verse_end: 12, name: "Melchisedec King Salem Priest Most High" },
  { chapter: 7, verse_start: 13, verse_end: 28, name: "Things Spoken Pertaineth Another Tribe No" },
  { chapter: 8, verse_start: 1, verse_end: 13, name: "Now Things Have Spoken Sum Have" },
  { chapter: 9, verse_start: 1, verse_end: 12, name: "Then Verily First Covenant Had Also" },
  { chapter: 9, verse_start: 13, verse_end: 28, name: "If Blood Bulls Goats Ashes An" },
  { chapter: 10, verse_start: 1, verse_end: 12, name: "Law Having Shadow Good Things Come" },
  { chapter: 10, verse_start: 13, verse_end: 24, name: "Henceforth Expecting Till Enemies Made Footstool" },
  { chapter: 10, verse_start: 25, verse_end: 39, name: "Not Forsaking Assembling Ourselves Together Manner" },
  { chapter: 11, verse_start: 1, verse_end: 12, name: "Now Faith Substance Things Hoped Evidence" },
  { chapter: 11, verse_start: 13, verse_end: 24, name: "All Died Faith Not Having Received" },
  { chapter: 11, verse_start: 25, verse_end: 40, name: "Choosing Rather Suffer Affliction People God" },
  { chapter: 12, verse_start: 1, verse_end: 12, name: "Wherefore Seeing Also Compassed About So" },
  { chapter: 12, verse_start: 13, verse_end: 29, name: "Make Straight Paths Feet Lest Lame" },
  { chapter: 13, verse_start: 1, verse_end: 12, name: "Let Brotherly Love Continue" },
  { chapter: 13, verse_start: 13, verse_end: 25, name: "Let Us Go Forth Therefore Unto" }
];
