// Auto-generated pericopes for James (book 59)
// Generated by scripts/generate_pericopes_from_db.js

export const JAMES_PERICOPES = [
  { chapter: 1, verse_start: 1, verse_end: 12, name: "James Servant God Lord Jesus Christ" },
  { chapter: 1, verse_start: 13, verse_end: 27, name: "Let No Man Say When Tempted" },
  { chapter: 2, verse_start: 1, verse_end: 12, name: "My Brethren Have Not Faith Lord" },
  { chapter: 2, verse_start: 13, verse_end: 26, name: "Have Judgment Without Mercy Hath Shewed" },
  { chapter: 3, verse_start: 1, verse_end: 12, name: "My Brethren Not Many Masters Knowing" },
  { chapter: 3, verse_start: 13, verse_end: 18, name: "Wise Man Endued Knowledge Among Let" },
  { chapter: 4, verse_start: 1, verse_end: 17, name: "Whence Come Wars Fightings Among Come" },
  { chapter: 5, verse_start: 1, verse_end: 12, name: "Go Now Ye Rich Men Weep" },
  { chapter: 5, verse_start: 13, verse_end: 20, name: "Any Among Afflicted Let Him Pray" }
];
