// Auto-generated pericopes for 1 Peter (book 60)
// Generated by scripts/generate_pericopes_from_db.js

export const PETER1_PERICOPES = [
  { chapter: 1, verse_start: 1, verse_end: 12, name: "Peter An Apostle Jesus Christ Strangers" },
  { chapter: 1, verse_start: 13, verse_end: 25, name: "Wherefore Gird Up Loins Mind Sober" },
  { chapter: 2, verse_start: 1, verse_end: 12, name: "Wherefore Laying Aside All Malice All" },
  { chapter: 2, verse_start: 13, verse_end: 25, name: "Submit Yourselves Every Ordinance Man Lords" },
  { chapter: 3, verse_start: 1, verse_end: 12, name: "Likewise Ye Wives Subjection Own Husbands" },
  { chapter: 3, verse_start: 13, verse_end: 22, name: "Will Harm If Ye Followers Good" },
  { chapter: 4, verse_start: 1, verse_end: 12, name: "Forasmuch Then Christ Hath Suffered Us" },
  { chapter: 4, verse_start: 13, verse_end: 19, name: "But Rejoice Inasmuch Ye Partakers Christs" },
  { chapter: 5, verse_start: 1, verse_end: 14, name: "Elders Among Exhort Am Also An" }
];
