// Auto-generated pericopes for 2 Peter (book 61)
// Generated by scripts/generate_pericopes_from_db.js

export const PETER2_PERICOPES = [
  { chapter: 1, verse_start: 1, verse_end: 12, name: "Simon Peter Servant An Apostle Jesus" },
  { chapter: 1, verse_start: 13, verse_end: 21, name: "Yea Think Meet Long Am Tabernacle" },
  { chapter: 2, verse_start: 1, verse_end: 12, name: "But There False Prophets Also Among" },
  { chapter: 2, verse_start: 13, verse_end: 22, name: "Receive Reward Unrighteousness Count Pleasure Riot" },
  { chapter: 3, verse_start: 1, verse_end: 12, name: "Second Epistle Beloved Now Write Unto" },
  { chapter: 3, verse_start: 13, verse_end: 18, name: "Nevertheless According Promise Look New Heavens" }
];
