// Auto-generated pericopes for 1 John (book 62)
// Generated by scripts/generate_pericopes_from_db.js

export const JOHN1_PERICOPES = [
  { chapter: 1, verse_start: 1, verse_end: 10, name: "Beginning Have Heard Have Seen Eyes" },
  { chapter: 2, verse_start: 1, verse_end: 12, name: "My Little Children Things Write Unto" },
  { chapter: 2, verse_start: 13, verse_end: 29, name: "Write Unto Fathers Because Ye Have" },
  { chapter: 3, verse_start: 1, verse_end: 12, name: "Behold What Manner Love Father Hath" },
  { chapter: 3, verse_start: 13, verse_end: 24, name: "Marvel Not My Brethren If World" },
  { chapter: 4, verse_start: 1, verse_end: 12, name: "Beloved Believe Not Every Spirit But" },
  { chapter: 4, verse_start: 13, verse_end: 21, name: "Hereby Know Dwell Him Us Because" },
  { chapter: 5, verse_start: 1, verse_end: 12, name: "Whosoever Believeth Jesus Christ Born God" },
  { chapter: 5, verse_start: 13, verse_end: 21, name: "Things Have Written Unto Believe Name" }
];
