// Auto-generated pericopes for 2 John (book 63)
// Generated by scripts/generate_pericopes_from_db.js

export const JOHN2_PERICOPES = [
  { chapter: 1, verse_start: 1, verse_end: 13, name: "Elder Unto Elect Lady Children Love" }
];
