// Auto-generated pericopes for 3 John (book 64)
// Generated by scripts/generate_pericopes_from_db.js

export const JOHN3_PERICOPES = [
  { chapter: 1, verse_start: 1, verse_end: 14, name: "Elder Unto Wellbeloved Gaius Love Truth" }
];
