// Auto-generated pericopes for Jude (book 65)
// Generated by scripts/generate_pericopes_from_db.js

export const JUDE_PERICOPES = [
  { chapter: 1, verse_start: 1, verse_end: 12, name: "Jude Servant Jesus Christ Brother James" },
  { chapter: 1, verse_start: 13, verse_end: 25, name: "Raging Waves Sea Foaming Out Own" }
];
