export const JOSHUA_PERICOPES = [
  { chapter: 1, verse_start: 1, verse_end: 18, name: 'Be Strong and Courageous' },
  { chapter: 2, verse_start: 1, verse_end: 24, name: 'Rahab and the Spies' },
  { chapter: 3, verse_start: 1, verse_end: 17, name: 'Crossing the Jordan' },
  { chapter: 4, verse_start: 1, verse_end: 24, name: 'Twelve Stones' },
  { chapter: 5, verse_start: 1, verse_end: 15, name: 'Commander of the Lord\'s Army' },
  { chapter: 6, verse_start: 1, verse_end: 27, name: 'The Fall of Jericho' },
  { chapter: 7, verse_start: 1, verse_end: 26, name: 'Achan\'s Sin' },
  { chapter: 8, verse_start: 1, verse_end: 35, name: 'The Conquest of Ai' },
  { chapter: 9, verse_start: 1, verse_end: 27, name: 'The Gibeonite Deception' },
  { chapter: 10, verse_start: 1, verse_end: 43, name: 'The Sun Stood Still' },
  { chapter: 11, verse_start: 1, verse_end: 23, name: 'Conquest of the North' },
  { chapter: 12, verse_start: 1, verse_end: 24, name: 'List of Defeated Kings' },
  { chapter: 13, verse_start: 1, verse_end: 33, name: 'Land Yet to Be Conquered' },
  { chapter: 14, verse_start: 1, verse_end: 15, name: 'Caleb\'s Inheritance' },
  { chapter: 15, verse_start: 1, verse_end: 63, name: 'Territory of Judah' },
  { chapter: 16, verse_start: 1, verse_end: 10, name: 'Territory of Ephraim' },
  { chapter: 17, verse_start: 1, verse_end: 18, name: 'Territory of Manasseh' },
  { chapter: 18, verse_start: 1, verse_end: 28, name: 'Dividing the Remaining Land' },
  { chapter: 19, verse_start: 1, verse_end: 51, name: 'Inheritances of the Tribes' },
  { chapter: 20, verse_start: 1, verse_end: 9, name: 'Cities of Refuge' },
  { chapter: 21, verse_start: 1, verse_end: 45, name: 'Cities for the Levites' },
  { chapter: 22, verse_start: 1, verse_end: 34, name: 'The Altar of Witness' },
  { chapter: 23, verse_start: 1, verse_end: 16, name: 'Joshua\'s Farewell' },
  { chapter: 24, verse_start: 1, verse_end: 33, name: 'Choose This Day Whom You Serve' },
];
