export const SAMUEL1_PERICOPES = [
  // Samuel's Birth and Call
  { chapter: 1, verse_start: 1, verse_end: 28, name: 'Hannah\'s Prayer' },
  { chapter: 2, verse_start: 1, verse_end: 36, name: 'Hannah\'s Song' },
  { chapter: 3, verse_start: 1, verse_end: 21, name: 'The Lord Calls Samuel' },
  { chapter: 4, verse_start: 1, verse_end: 22, name: 'The Ark Captured' },
  { chapter: 5, verse_start: 1, verse_end: 12, name: 'Dagon Falls' },
  { chapter: 6, verse_start: 1, verse_end: 21, name: 'The Ark Returned' },
  { chapter: 7, verse_start: 1, verse_end: 17, name: 'Samuel Judges Israel' },
  // Saul Becomes King
  { chapter: 8, verse_start: 1, verse_end: 22, name: 'Israel Demands a King' },
  { chapter: 9, verse_start: 1, verse_end: 27, name: 'Saul Chosen' },
  { chapter: 10, verse_start: 1, verse_end: 27, name: 'Saul Anointed' },
  { chapter: 11, verse_start: 1, verse_end: 15, name: 'Saul Defeats the Ammonites' },
  { chapter: 12, verse_start: 1, verse_end: 25, name: 'Samuel\'s Farewell' },
  { chapter: 13, verse_start: 1, verse_end: 23, name: 'Saul\'s Presumptuous Offering' },
  { chapter: 14, verse_start: 1, verse_end: 52, name: 'Jonathan\'s Victory' },
  { chapter: 15, verse_start: 1, verse_end: 35, name: 'Saul Rejected as King' },
  // David Anointed
  { chapter: 16, verse_start: 1, verse_end: 23, name: 'David Anointed' },
  { chapter: 17, verse_start: 1, verse_end: 58, name: 'David and Goliath' },
  { chapter: 18, verse_start: 1, verse_end: 30, name: 'Saul\'s Jealousy' },
  { chapter: 19, verse_start: 1, verse_end: 24, name: 'David Escapes' },
  { chapter: 20, verse_start: 1, verse_end: 42, name: 'Jonathan\'s Loyalty' },
  { chapter: 21, verse_start: 1, verse_end: 15, name: 'David at Nob' },
  { chapter: 22, verse_start: 1, verse_end: 23, name: 'Saul Kills the Priests' },
  { chapter: 23, verse_start: 1, verse_end: 29, name: 'David Spares Saul at Keilah' },
  { chapter: 24, verse_start: 1, verse_end: 22, name: 'David Spares Saul' },
  { chapter: 25, verse_start: 1, verse_end: 44, name: 'David and Abigail' },
  { chapter: 26, verse_start: 1, verse_end: 25, name: 'David Spares Saul Again' },
  { chapter: 27, verse_start: 1, verse_end: 12, name: 'David Among the Philistines' },
  { chapter: 28, verse_start: 1, verse_end: 25, name: 'Saul and the Medium' },
  { chapter: 29, verse_start: 1, verse_end: 11, name: 'Philistines Reject David' },
  { chapter: 30, verse_start: 1, verse_end: 31, name: 'David Defeats the Amalekites' },
  { chapter: 31, verse_start: 1, verse_end: 13, name: 'The Death of Saul' },
];
