export const CHRONICLES2_PERICOPES = [
  { chapter: 1, verse_start: 1, verse_end: 17, name: 'Solomon Asks for Wisdom' },
  { chapter: 2, verse_start: 1, verse_end: 18, name: 'Preparations for Temple' },
  { chapter: 3, verse_start: 1, verse_end: 17, name: 'Building the Temple' },
  { chapter: 4, verse_start: 1, verse_end: 22, name: 'Temple Furnishings' },
  { chapter: 5, verse_start: 1, verse_end: 14, name: 'The Ark Brought In' },
  { chapter: 6, verse_start: 1, verse_end: 42, name: 'Solomon\'s Prayer' },
  { chapter: 7, verse_start: 1, verse_end: 22, name: 'Dedication of the Temple' },
  { chapter: 8, verse_start: 1, verse_end: 18, name: 'Solomon\'s Activities' },
  { chapter: 9, verse_start: 1, verse_end: 31, name: 'Queen of Sheba Visits' },
  { chapter: 10, verse_start: 1, verse_end: 19, name: 'The Kingdom Divided' },
  { chapter: 11, verse_start: 1, verse_end: 23, name: 'Rehoboam Strengthens Judah' },
  { chapter: 12, verse_start: 1, verse_end: 16, name: 'Egypt Invades' },
  { chapter: 13, verse_start: 1, verse_end: 22, name: 'Abijah Reigns' },
  { chapter: 14, verse_start: 1, verse_end: 15, name: 'Asa\'s Reforms' },
  { chapter: 15, verse_start: 1, verse_end: 19, name: 'Asa\'s Covenant' },
  { chapter: 16, verse_start: 1, verse_end: 14, name: 'Asa\'s Decline' },
  { chapter: 17, verse_start: 1, verse_end: 19, name: 'Jehoshaphat\'s Reign' },
  { chapter: 18, verse_start: 1, verse_end: 34, name: 'Micaiah Prophesies' },
  { chapter: 19, verse_start: 1, verse_end: 11, name: 'Jehoshaphat\'s Reforms' },
  { chapter: 20, verse_start: 1, verse_end: 37, name: 'Victory Through Praise' },
  { chapter: 21, verse_start: 1, verse_end: 20, name: 'Jehoram\'s Wicked Reign' },
  { chapter: 22, verse_start: 1, verse_end: 12, name: 'Ahaziah Killed' },
  { chapter: 23, verse_start: 1, verse_end: 21, name: 'Joash Made King' },
  { chapter: 24, verse_start: 1, verse_end: 27, name: 'Joash Repairs the Temple' },
  { chapter: 25, verse_start: 1, verse_end: 28, name: 'Amaziah Reigns' },
  { chapter: 26, verse_start: 1, verse_end: 23, name: 'Uzziah\'s Pride' },
  { chapter: 27, verse_start: 1, verse_end: 9, name: 'Jotham Reigns' },
  { chapter: 28, verse_start: 1, verse_end: 27, name: 'Ahaz\'s Apostasy' },
  { chapter: 29, verse_start: 1, verse_end: 36, name: 'Hezekiah Cleanses the Temple' },
  { chapter: 30, verse_start: 1, verse_end: 27, name: 'The Great Passover' },
  { chapter: 31, verse_start: 1, verse_end: 21, name: 'Hezekiah\'s Reforms' },
  { chapter: 32, verse_start: 1, verse_end: 33, name: 'Sennacherib Invades' },
  { chapter: 33, verse_start: 1, verse_end: 25, name: 'Manasseh and Amon' },
  { chapter: 34, verse_start: 1, verse_end: 33, name: 'Josiah\'s Reforms' },
  { chapter: 35, verse_start: 1, verse_end: 27, name: 'Josiah Celebrates Passover' },
  { chapter: 36, verse_start: 1, verse_end: 23, name: 'The Fall of Jerusalem' },
];
