export const JOB_PERICOPES = [
  { chapter: 1, verse_start: 1, verse_end: 22, name: 'Job Tested' },
  { chapter: 2, verse_start: 1, verse_end: 13, name: 'Job\'s Second Test' },
  { chapter: 3, verse_start: 1, verse_end: 26, name: 'Job Curses His Birth' },
  { chapter: 4, verse_start: 1, verse_end: 21, name: 'Eliphaz Speaks' },
  { chapter: 5, verse_start: 1, verse_end: 27, name: 'Man Is Born to Trouble' },
  { chapter: 6, verse_start: 1, verse_end: 30, name: 'Job Replies to Eliphaz' },
  { chapter: 7, verse_start: 1, verse_end: 21, name: 'My Life Is a Breath' },
  { chapter: 8, verse_start: 1, verse_end: 22, name: 'Bildad Speaks' },
  { chapter: 9, verse_start: 1, verse_end: 35, name: 'Job Replies to Bildad' },
  { chapter: 10, verse_start: 1, verse_end: 22, name: 'I Loathe My Life' },
  { chapter: 11, verse_start: 1, verse_end: 20, name: 'Zophar Speaks' },
  { chapter: 12, verse_start: 1, verse_end: 25, name: 'Job Replies to Zophar' },
  { chapter: 13, verse_start: 1, verse_end: 28, name: 'Though He Slay Me' },
  { chapter: 14, verse_start: 1, verse_end: 22, name: 'Man Born of Woman' },
  { chapter: 15, verse_start: 1, verse_end: 35, name: 'Eliphaz\'s Second Speech' },
  { chapter: 16, verse_start: 1, verse_end: 22, name: 'Job\'s Response' },
  { chapter: 17, verse_start: 1, verse_end: 16, name: 'My Spirit Is Broken' },
  { chapter: 18, verse_start: 1, verse_end: 21, name: 'Bildad\'s Second Speech' },
  { chapter: 19, verse_start: 1, verse_end: 29, name: 'I Know My Redeemer Lives' },
  { chapter: 20, verse_start: 1, verse_end: 29, name: 'Zophar\'s Second Speech' },
  { chapter: 21, verse_start: 1, verse_end: 34, name: 'Job\'s Response' },
  { chapter: 22, verse_start: 1, verse_end: 30, name: 'Eliphaz\'s Third Speech' },
  { chapter: 23, verse_start: 1, verse_end: 17, name: 'Job Seeks God' },
  { chapter: 24, verse_start: 1, verse_end: 25, name: 'Why Are Times Not Set?' },
  { chapter: 25, verse_start: 1, verse_end: 6, name: 'Bildad\'s Third Speech' },
  { chapter: 26, verse_start: 1, verse_end: 14, name: 'Job\'s Response' },
  { chapter: 27, verse_start: 1, verse_end: 23, name: 'I Hold Fast My Integrity' },
  { chapter: 28, verse_start: 1, verse_end: 28, name: 'Where Is Wisdom Found?' },
  { chapter: 29, verse_start: 1, verse_end: 25, name: 'Job\'s Former Blessings' },
  { chapter: 30, verse_start: 1, verse_end: 31, name: 'Job\'s Present Misery' },
  { chapter: 31, verse_start: 1, verse_end: 40, name: 'Job\'s Final Defense' },
  { chapter: 32, verse_start: 1, verse_end: 22, name: 'Elihu Speaks' },
  { chapter: 33, verse_start: 1, verse_end: 33, name: 'God Speaks in Dreams' },
  { chapter: 34, verse_start: 1, verse_end: 37, name: 'God Is Just' },
  { chapter: 35, verse_start: 1, verse_end: 16, name: 'What Do You Gain?' },
  { chapter: 36, verse_start: 1, verse_end: 33, name: 'God\'s Power' },
  { chapter: 37, verse_start: 1, verse_end: 24, name: 'God\'s Majesty' },
  { chapter: 38, verse_start: 1, verse_end: 41, name: 'The Lord Answers Job' },
  { chapter: 39, verse_start: 1, verse_end: 30, name: 'Do You Give the Horse Strength?' },
  { chapter: 40, verse_start: 1, verse_end: 24, name: 'Behold Behemoth' },
  { chapter: 41, verse_start: 1, verse_end: 34, name: 'Can You Draw Out Leviathan?' },
  { chapter: 42, verse_start: 1, verse_end: 17, name: 'Job Repents and Is Restored' },
];
