export const HEBREWS_PERICOPES = [
  { chapter: 1, verse_start: 1, verse_end: 14, name: 'God Spoke by His Son' },
  { chapter: 2, verse_start: 1, verse_end: 18, name: 'Do Not Neglect So Great Salvation' },
  { chapter: 3, verse_start: 1, verse_end: 19, name: 'Today If You Hear His Voice' },
  { chapter: 4, verse_start: 1, verse_end: 13, name: 'Let Us Strive to Enter Rest' },
  { chapter: 4, verse_start: 14, verse_end: 16, name: 'Great High Priest' },
  { chapter: 5, verse_start: 1, verse_end: 14, name: 'Called by God' },
  { chapter: 6, verse_start: 1, verse_end: 20, name: 'Sure and Steadfast Anchor' },
  { chapter: 7, verse_start: 1, verse_end: 28, name: 'Priest Forever After Melchizedek' },
  { chapter: 8, verse_start: 1, verse_end: 13, name: 'The New Covenant' },
  { chapter: 9, verse_start: 1, verse_end: 28, name: 'Christ Entered Once for All' },
  { chapter: 10, verse_start: 1, verse_end: 18, name: 'By One Offering Perfected Forever' },
  { chapter: 10, verse_start: 19, verse_end: 39, name: 'Draw Near with a True Heart' },
  { chapter: 11, verse_start: 1, verse_end: 7, name: 'Faith Is the Assurance' },
  { chapter: 11, verse_start: 8, verse_end: 22, name: 'Abraham Looked Forward' },
  { chapter: 11, verse_start: 23, verse_end: 31, name: 'Moses Chose to Be Mistreated' },
  { chapter: 11, verse_start: 32, verse_end: 40, name: 'Time Would Fail Me' },
  { chapter: 12, verse_start: 1, verse_end: 17, name: 'Looking to Jesus' },
  { chapter: 12, verse_start: 18, verse_end: 29, name: 'A Kingdom That Cannot Be Shaken' },
  { chapter: 13, verse_start: 1, verse_end: 25, name: 'Let Brotherly Love Continue' },
];
