#!/usr/bin/env python3
"""
KJV Bible Text Importer
Parses KJV text file and generates SQL for importing into Supabase
"""

import re
import sys
from pathlib import Path

# Book name normalization (from file format to our database format)
BOOK_NAME_MAP = {
    'Genesis': 'Genesis',
    'Exodus': 'Exodus',
    'Leviticus': 'Leviticus',
    'Numbers': 'Numbers',
    'Deuteronomy': 'Deuteronomy',
    'Joshua': 'Joshua',
    'Judges': 'Judges',
    'Ruth': 'Ruth',
    '1 Samuel': '1 Samuel',
    '2 Samuel': '2 Samuel',
    '1 Kings': '1 Kings',
    '2 Kings': '2 Kings',
    '1 Chronicles': '1 Chronicles',
    '2 Chronicles': '2 Chronicles',
    'Ezra': 'Ezra',
    'Nehemiah': 'Nehemiah',
    'Esther': 'Esther',
    'Job': 'Job',
    'Psalm': 'Psalms',  # File uses singular "Psalm"
    'Psalms': 'Psalms',
    'Proverbs': 'Proverbs',
    'Ecclesiastes': 'Ecclesiastes',
    'Song of Solomon': 'Song of Solomon',
    'Isaiah': 'Isaiah',
    'Jeremiah': 'Jeremiah',
    'Lamentations': 'Lamentations',
    'Ezekiel': 'Ezekiel',
    'Daniel': 'Daniel',
    'Hosea': 'Hosea',
    'Joel': 'Joel',
    'Amos': 'Amos',
    'Obadiah': 'Obadiah',
    'Jonah': 'Jonah',
    'Micah': 'Micah',
    'Nahum': 'Nahum',
    'Habakkuk': 'Habakkuk',
    'Zephaniah': 'Zephaniah',
    'Haggai': 'Haggai',
    'Zechariah': 'Zechariah',
    'Malachi': 'Malachi',
    'Matthew': 'Matthew',
    'Mark': 'Mark',
    'Luke': 'Luke',
    'John': 'John',
    'Acts': 'Acts',
    'Romans': 'Romans',
    '1 Corinthians': '1 Corinthians',
    '2 Corinthians': '2 Corinthians',
    'Galatians': 'Galatians',
    'Ephesians': 'Ephesians',
    'Philippians': 'Philippians',
    'Colossians': 'Colossians',
    '1 Thessalonians': '1 Thessalonians',
    '2 Thessalonians': '2 Thessalonians',
    '1 Timothy': '1 Timothy',
    '2 Timothy': '2 Timothy',
    'Titus': 'Titus',
    'Philemon': 'Philemon',
    'Hebrews': 'Hebrews',
    'James': 'James',
    '1 Peter': '1 Peter',
    '2 Peter': '2 Peter',
    '1 John': '1 John',
    '2 John': '2 John',
    '3 John': '3 John',
    'Jude': 'Jude',
    'Revelation': 'Revelation',
}

def escape_sql_string(text):
    """Escape single quotes for SQL"""
    return text.replace("'", "''")

def parse_kjv_file(file_path):
    """Parse KJV text file and yield verse data"""
    with open(file_path, 'r', encoding='utf-8') as f:
        for line_num, line in enumerate(f, 1):
            line = line.strip()

            # Skip header lines and empty lines
            if not line or line.startswith('KJV') or line.startswith('King James'):
                continue

            # Parse format: "Book Chapter:Verse\tText"
            match = re.match(r'^(.+?)\s+(\d+):(\d+)\t(.+)$', line)
            if not match:
                print(f"Warning: Skipping line {line_num}: {line[:50]}...", file=sys.stderr)
                continue

            book_name, chapter, verse, text = match.groups()

            # Normalize book name
            if book_name not in BOOK_NAME_MAP:
                print(f"Warning: Unknown book '{book_name}' at line {line_num}", file=sys.stderr)
                continue

            yield {
                'book': BOOK_NAME_MAP[book_name],
                'chapter': int(chapter),
                'verse': int(verse),
                'text': text
            }

def generate_sql_inserts(verses, batch_size=1000):
    """Generate SQL INSERT statements in batches"""

    print("-- KJV Bible Verses Import")
    print("-- Generated by import_kjv.py\n")
    print("-- Get version and book IDs")
    print("DO $$")
    print("DECLARE")
    print("  v_kjv_id UUID;")
    print("  v_book_ids UUID[];")
    print("BEGIN")
    print("  -- Get KJV version ID")
    print("  SELECT id INTO v_kjv_id FROM bible_versions WHERE abbreviation = 'KJV';")
    print()
    print("  -- Get all book IDs (in order)")
    print("  SELECT array_agg(id ORDER BY book_number) INTO v_book_ids FROM bible_books;")
    print()

    verse_count = 0
    batch = []

    for verse in verses:
        # Get book index (1-based)
        book_list = list(BOOK_NAME_MAP.values())
        try:
            book_idx = book_list.index(verse['book']) + 1
        except ValueError:
            continue

        # Escape text for SQL
        text_escaped = escape_sql_string(verse['text'])

        # Build insert value
        insert_value = f"(v_kjv_id, v_book_ids[{book_idx}], {verse['chapter']}, {verse['verse']}, '{text_escaped}')"
        batch.append(insert_value)
        verse_count += 1

        # Write batch when full
        if len(batch) >= batch_size:
            print(f"  -- Batch insert ({verse_count - len(batch) + 1} to {verse_count})")
            print(f"  INSERT INTO bible_verses (version_id, book_id, chapter, verse, text)")
            print(f"  VALUES")
            print("    " + ",\n    ".join(batch))
            print("  ON CONFLICT (version_id, book_id, chapter, verse) DO NOTHING;")
            print()
            batch = []

    # Write remaining verses
    if batch:
        print(f"  -- Final batch ({verse_count - len(batch) + 1} to {verse_count})")
        print(f"  INSERT INTO bible_verses (version_id, book_id, chapter, verse, text)")
        print(f"  VALUES")
        print("    " + ",\n    ".join(batch))
        print("  ON CONFLICT (version_id, book_id, chapter, verse) DO NOTHING;")
        print()

    print("END $$;")
    print()
    print(f"-- Total verses imported: {verse_count}")

def main():
    if len(sys.argv) < 2:
        print("Usage: python import_kjv.py <kjv_text_file>", file=sys.stderr)
        print("Example: python import_kjv.py '/home/nigel/Downloads/First Letter/KJV King James Bible.txt'", file=sys.stderr)
        sys.exit(1)

    input_file = sys.argv[1]

    if not Path(input_file).exists():
        print(f"Error: File not found: {input_file}", file=sys.stderr)
        sys.exit(1)

    print(f"-- Parsing {input_file}...", file=sys.stderr)
    verses = list(parse_kjv_file(input_file))
    print(f"-- Found {len(verses)} verses", file=sys.stderr)

    generate_sql_inserts(verses)

if __name__ == '__main__':
    main()
