/**
 * GENESIS PERICOPES
 * Converted from memory-method-bible comprehensive research outlines
 * Optimized for memorization: text-driven boundaries, evocative titles
 */

export const GENESIS_PERICOPES = [
  { chapter: 1, verse_start: 1, verse_end: 2, name: 'Prologue: The Primal State' },
  { chapter: 1, verse_start: 3, verse_end: 5, name: 'Day 1: Creation of Light' },
  { chapter: 1, verse_start: 6, verse_end: 8, name: 'Day 2: Firmament' },
  { chapter: 1, verse_start: 9, verse_end: 10, name: 'Waters Gathered, Land Appears' },
  { chapter: 1, verse_start: 11, verse_end: 13, name: 'Vegetation Spreads Across the Land' },
  { chapter: 1, verse_start: 14, verse_end: 19, name: 'Day 4: Luminaries' },
  { chapter: 1, verse_start: 20, verse_end: 23, name: 'Day 5: Birds and Fish' },
  { chapter: 1, verse_start: 24, verse_end: 31, name: 'Day 6: Animals and Humans' },
  { chapter: 2, verse_start: 1, verse_end: 3, name: 'Day 7: Sabbath Rest' },
  { chapter: 2, verse_start: 4, verse_end: 7, name: 'Introduction and Creation of Man' },
  { chapter: 2, verse_start: 8, verse_end: 17, name: 'The Garden, Trees, and Command' },
  { chapter: 2, verse_start: 18, verse_end: 20, name: 'The Search for a Helper' },
  { chapter: 2, verse_start: 21, verse_end: 25, name: 'The Creation of Woman' },
  { chapter: 3, verse_start: 1, verse_end: 5, name: 'The Serpent\'s Temptation' },
  { chapter: 3, verse_start: 6, verse_end: 7, name: 'The Disobedience' },
  { chapter: 3, verse_start: 8, verse_end: 13, name: 'The Confrontation and Blame' },
  { chapter: 3, verse_start: 14, verse_end: 19, name: 'The Curses' },
  { chapter: 3, verse_start: 20, verse_end: 21, name: 'Eve\'s Naming and God\'s Provision' },
  { chapter: 3, verse_start: 22, verse_end: 24, name: 'The Expulsion' },
  { chapter: 4, verse_start: 1, verse_end: 5, name: 'The Two Brothers and Their Offerings' },
  { chapter: 4, verse_start: 6, verse_end: 7, name: 'God\'s Warning to Cain' },
  { chapter: 4, verse_start: 9, verse_end: 16, name: 'The Confrontation and Curse' },
  { chapter: 4, verse_start: 17, verse_end: 24, name: 'The Genealogy of Cain' },
  { chapter: 4, verse_start: 25, verse_end: 26, name: 'The Birth of Seth and Hope' },
  { chapter: 6, verse_start: 9, verse_end: 12, name: 'Noah and the Corrupt Earth' },
  { chapter: 6, verse_start: 13, verse_end: 22, name: 'First Speech: Judgment and Build Command' },
  { chapter: 7, verse_start: 1, verse_end: 5, name: 'Second Speech: Enter Command' },
  { chapter: 7, verse_start: 6, verse_end: 16, name: 'Boarding the Ark' },
  { chapter: 7, verse_start: 17, verse_end: 24, name: 'The Flood Waters Rise' },
  { chapter: 8, verse_start: 1, verse_end: 5, name: 'Chiastic Center: God Remembers Noah' },
  { chapter: 8, verse_start: 6, verse_end: 12, name: 'The Raven and the Dove' },
  { chapter: 8, verse_start: 13, verse_end: 14, name: 'The Earth is Dry' },
  { chapter: 8, verse_start: 15, verse_end: 19, name: 'Leaving the Ark' },
  { chapter: 8, verse_start: 20, verse_end: 22, name: 'Noah\'s Sacrifice and God\'s Promise' },
  { chapter: 9, verse_start: 1, verse_end: 7, name: 'The New Blessing (Re-Creation)' },
  { chapter: 9, verse_start: 8, verse_end: 17, name: 'The Noahic Covenant and Rainbow' },
  { chapter: 9, verse_start: 18, verse_end: 29, name: 'Epilogue: Noah\'s Drunkenness and Canaan\'s Curse' },
  { chapter: 11, verse_start: 1, verse_end: 4, name: 'Humanity\'s United Plan' },
  { chapter: 11, verse_start: 5, verse_end: 7, name: 'YHWH\'s Descent and Monologue' },
  { chapter: 11, verse_start: 8, verse_end: 9, name: 'The Scattering and Etiological Conclusion' },
  { chapter: 11, verse_start: 27, verse_end: 32, name: 'Terah\'s Toledot and Barrenness' },
  { chapter: 12, verse_start: 1, verse_end: 9, name: 'The Call and Threefold Promise' },
  { chapter: 12, verse_start: 10, verse_end: 20, name: 'Obstacle 1: Wife-Sister in Egypt' },
  { chapter: 13, verse_start: 1, verse_end: 18, name: 'Obstacle 2: Separation from Lot' },
  { chapter: 14, verse_start: 1, verse_end: 24, name: 'War of Kings and Melchizedek' },
  { chapter: 15, verse_start: 1, verse_end: 21, name: 'The Covenant of the Pieces' },
  { chapter: 16, verse_start: 1, verse_end: 16, name: 'Obstacle 3: Birth of Ishmael' },
  { chapter: 17, verse_start: 1, verse_end: 27, name: 'Covenant of Circumcision' },
  { chapter: 18, verse_start: 1, verse_end: 15, name: 'The Three Visitors' },
  { chapter: 18, verse_start: 16, verse_end: 33, name: 'Abraham Intercedes for Sodom' },
  { chapter: 19, verse_start: 1, verse_end: 38, name: 'The Destruction of Sodom' },
  { chapter: 20, verse_start: 1, verse_end: 18, name: 'Obstacle 4: Wife-Sister in Gerar' },
  { chapter: 21, verse_start: 1, verse_end: 7, name: 'The Birth of Isaac' },
  { chapter: 21, verse_start: 8, verse_end: 21, name: 'Obstacle 5: Expulsion of Ishmael' },
  { chapter: 22, verse_start: 1, verse_end: 2, name: 'The Agonizing Command' },
  { chapter: 22, verse_start: 3, verse_end: 6, name: 'The Silent Journey' },
  { chapter: 22, verse_start: 7, verse_end: 8, name: 'The Dialogue (Where is the lamb?)' },
  { chapter: 22, verse_start: 9, verse_end: 14, name: 'The Intervention and Provision' },
  { chapter: 22, verse_start: 15, verse_end: 19, name: 'The Oath and Return' },
  { chapter: 23, verse_start: 1, verse_end: 20, name: 'Sarah\'s Death and Burial' },
  { chapter: 24, verse_start: 1, verse_end: 67, name: 'A Wife for Isaac' },
  { chapter: 25, verse_start: 1, verse_end: 11, name: 'The Death of Abraham' },
  { chapter: 25, verse_start: 19, verse_end: 28, name: 'The Birth of Struggling Twins' },
  { chapter: 25, verse_start: 29, verse_end: 34, name: 'Jacob Gets the Birthright' },
  { chapter: 26, verse_start: 1, verse_end: 35, name: 'Isaac\'s Covenant and Conflict' },
  { chapter: 27, verse_start: 1, verse_end: 40, name: 'Jacob Steals the Blessing' },
  { chapter: 28, verse_start: 10, verse_end: 22, name: 'The Bethel Ladder Vision' },
  { chapter: 29, verse_start: 1, verse_end: 30, name: 'Jacob\'s Marriage to Leah and Rachel' },
  { chapter: 30, verse_start: 25, verse_end: 43, name: 'Jacob Outwits Laban and Prospers' },
  { chapter: 31, verse_start: 1, verse_end: 55, name: 'Jacob Flees Laban and the Covenant' },
  { chapter: 32, verse_start: 1, verse_end: 21, name: 'Jacob Prepares to Meet Esau' },
  { chapter: 32, verse_start: 22, verse_end: 25, name: 'The Struggle' },
  { chapter: 32, verse_start: 26, verse_end: 29, name: 'The Blessing and Renaming' },
  { chapter: 32, verse_start: 30, verse_end: 32, name: 'The Scar of Faith' },
  { chapter: 33, verse_start: 1, verse_end: 20, name: 'Reconciliation with Esau' },
  { chapter: 34, verse_start: 1, verse_end: 31, name: 'The Violation of Dinah' },
  { chapter: 35, verse_start: 1, verse_end: 29, name: 'Jacob\'s Return to Bethel' },
  { chapter: 37, verse_start: 1, verse_end: 11, name: 'Joseph\'s Dreams and Brothers\' Hatred' },
  { chapter: 37, verse_start: 12, verse_end: 24, name: 'The Plot Against Joseph' },
  { chapter: 37, verse_start: 25, verse_end: 28, name: 'Joseph Sold into Slavery' },
  { chapter: 37, verse_start: 29, verse_end: 36, name: 'The Deception of Jacob' },
  { chapter: 38, verse_start: 1, verse_end: 30, name: 'The Interruption: Judah and Tamar' },
  { chapter: 39, verse_start: 1, verse_end: 23, name: 'Joseph and Potiphar\'s Wife' },
  { chapter: 40, verse_start: 1, verse_end: 23, name: 'The Dreams in Prison' },
  { chapter: 41, verse_start: 1, verse_end: 46, name: 'Pharaoh\'s Dreams and Joseph\'s Rise' },
  { chapter: 41, verse_start: 47, verse_end: 57, name: 'Joseph\'s Administration and Sons' },
  { chapter: 42, verse_start: 1, verse_end: 38, name: 'The Brothers\' First Trip' },
  { chapter: 43, verse_start: 1, verse_end: 14, name: 'The Brothers\' Second Trip' },
  { chapter: 43, verse_start: 15, verse_end: 34, name: 'The Feast in Egypt' },
  { chapter: 44, verse_start: 1, verse_end: 34, name: 'The Silver Cup Test' },
  { chapter: 45, verse_start: 1, verse_end: 3, name: 'The Revelation' },
  { chapter: 45, verse_start: 4, verse_end: 8, name: 'The Theological Re-framing' },
  { chapter: 45, verse_start: 9, verse_end: 15, name: 'The Commission and Reconciliation' },
  { chapter: 45, verse_start: 16, verse_end: 28, name: 'Pharaoh\'s Ratification' },
  { chapter: 46, verse_start: 1, verse_end: 34, name: 'Jacob\'s Descent into Egypt' },
  { chapter: 47, verse_start: 1, verse_end: 26, name: 'Joseph\'s Famine Policy' },
  { chapter: 47, verse_start: 27, verse_end: 31, name: 'Jacob\'s Final Request' },
  { chapter: 48, verse_start: 1, verse_end: 22, name: 'Jacob Blesses Ephraim and Manasseh' },
  { chapter: 49, verse_start: 1, verse_end: 32, name: 'Jacob\'s Final Blessing (Testament)' }
];
