/**
 * EXODUS PERICOPES
 * Converted from memory-method-bible comprehensive research outlines
 * Optimized for memorization: text-driven boundaries, evocative titles
 */

export const EXODUS_PERICOPES = [
  { chapter: 1, verse_start: 1, verse_end: 14, name: 'The Oppression Intensifies' },
  { chapter: 1, verse_start: 15, verse_end: 21, name: 'Hebrew Midwives\' Defiance' },
  { chapter: 2, verse_start: 1, verse_end: 10, name: 'Moses\' Birth and Rescue' },
  { chapter: 2, verse_start: 11, verse_end: 14, name: 'Moses Identifies with His People' },
  { chapter: 2, verse_start: 15, verse_end: 22, name: 'Moses Flees to Midian' },
  { chapter: 2, verse_start: 23, verse_end: 25, name: 'Israel\'s Cry Reaches God' },
  { chapter: 3, verse_start: 1, verse_end: 6, name: 'The Burning Bush Theophany' },
  { chapter: 3, verse_start: 7, verse_end: 10, name: 'God Reveals His Purpose' },
  { chapter: 3, verse_start: 11, verse_end: 15, name: 'The Name Revealed: I AM WHO I AM' },
  { chapter: 3, verse_start: 16, verse_end: 22, name: 'God\'s Sign to Moses' },
  { chapter: 4, verse_start: 1, verse_end: 9, name: 'Moses\' Signs of Authority' },
  { chapter: 4, verse_start: 10, verse_end: 13, name: 'Moses\' Eloquence Doubt' },
  { chapter: 4, verse_start: 14, verse_end: 17, name: 'Aaron Appointed as Moses\' Spokesman' },
  { chapter: 4, verse_start: 27, verse_end: 31, name: 'Moses\' Reunion with Aaron' },
  { chapter: 5, verse_start: 1, verse_end: 5, name: 'First Confrontation with Pharaoh' },
  { chapter: 5, verse_start: 6, verse_end: 9, name: 'Pharaoh\'s Cruel Response' },
  { chapter: 5, verse_start: 10, verse_end: 23, name: 'Israel Turns on Moses' },
  { chapter: 6, verse_start: 1, verse_end: 8, name: 'God Renews His Commitment' },
  { chapter: 6, verse_start: 9, verse_end: 13, name: 'Israel\'s Unbelief and Despair' },
  { chapter: 7, verse_start: 8, verse_end: 13, name: 'The Staff Before Pharaoh' },
  { chapter: 7, verse_start: 14, verse_end: 25, name: 'Plague 1: Water Turns to Blood' },
  { chapter: 8, verse_start: 1, verse_end: 15, name: 'Plague 2: Frogs Cover the Land' },
  { chapter: 8, verse_start: 16, verse_end: 19, name: 'Plague 3: Gnats/Lice Cover All Beings' },
  { chapter: 8, verse_start: 20, verse_end: 32, name: 'Plague 4: Swarms of Flies' },
  { chapter: 9, verse_start: 1, verse_end: 7, name: 'Plague 5: Disease on Livestock' },
  { chapter: 9, verse_start: 8, verse_end: 12, name: 'Plague 6: Boils on People and Animals' },
  { chapter: 9, verse_start: 13, verse_end: 35, name: 'Plague 7: Hail Destroys Crops' },
  { chapter: 10, verse_start: 1, verse_end: 20, name: 'Plague 8: Locusts Consume Remaining Crops' },
  { chapter: 10, verse_start: 21, verse_end: 29, name: 'Plague 9: Darkness Covers the Land' },
  { chapter: 11, verse_start: 1, verse_end: 10, name: 'The Tenth Plague Announced: Death of Firstborn' },
  { chapter: 12, verse_start: 1, verse_end: 14, name: 'The Passover Institution: God\'s Protection Plan' },
  { chapter: 12, verse_start: 15, verse_end: 28, name: 'Additional Passover Instructions: Unleavened Bread' },
  { chapter: 12, verse_start: 29, verse_end: 32, name: 'The Tenth Plague: Death of Egyptian Firstborn' },
  { chapter: 12, verse_start: 33, verse_end: 39, name: 'The Exodus: Israel Departs Egypt' },
  { chapter: 12, verse_start: 40, verse_end: 51, name: 'Generation Transition: From Egypt to Covenant' },
  { chapter: 13, verse_start: 1, verse_end: 16, name: 'Consecration of Firstborn and Unleavened Bread Laws' },
  { chapter: 13, verse_start: 17, verse_end: 22, name: 'The Route Changes: God Leads by Pillar' },
  { chapter: 14, verse_start: 1, verse_end: 14, name: 'Israel Trapped at Red Sea: Egyptian Pursuit' },
  { chapter: 14, verse_start: 15, verse_end: 31, name: 'The Red Sea Crossing: Deliverance Completed' },
  { chapter: 15, verse_start: 1, verse_end: 21, name: 'Song of Moses and Miriam\'s Celebratory Dance' },
  { chapter: 19, verse_start: 1, verse_end: 6, name: 'Arrival at Sinai and Covenant Proposal' },
  { chapter: 19, verse_start: 7, verse_end: 15, name: 'Preparation and Sanctification Protocol' },
  { chapter: 19, verse_start: 16, verse_end: 25, name: 'The Theophanic Descent: God\'s Awesome Presence' },
  { chapter: 20, verse_start: 1, verse_end: 17, name: 'The Ten Commandments: Covenant Foundation' },
  { chapter: 20, verse_start: 18, verse_end: 21, name: 'The People\'s Fear and Request for Mediation' },
  { chapter: 24, verse_start: 1, verse_end: 8, name: 'The Book of the Covenant Read and Accepted' },
  { chapter: 24, verse_start: 9, verse_end: 18, name: 'Moses Enters God\'s Presence on Mountain' },
  { chapter: 34, verse_start: 6, verse_end: 7, name: 'God\'s Character Revealed: Compassion and Justice' },
  { chapter: 34, verse_start: 10, verse_end: 27, name: 'Covenant Renewal Instructions' },
  { chapter: 34, verse_start: 29, verse_end: 35, name: 'Moses\' Radiant Face: Evidence of God\'s Presence' },
  { chapter: 34, verse_start: 1, verse_end: 5, name: 'God\'s Authority Over Egypt\'s Plagues Confirmed' },
  { chapter: 33, verse_start: 1, verse_end: 3, name: 'Land Conquest Promises Reaffirmed' },
  { chapter: 24, verse_start: 4, verse_end: 8, name: 'Covenant Establishment: Binding and Blessing Formula' },
  { chapter: 25, verse_start: 1, verse_end: 9, name: 'The Offering for the Sanctuary' },
  { chapter: 25, verse_start: 10, verse_end: 16, name: 'The Ark of the Covenant' },
  { chapter: 25, verse_start: 23, verse_end: 30, name: 'The Table for the Bread of the Presence' },
  { chapter: 25, verse_start: 31, verse_end: 39, name: 'The Golden Lampstand' },
  { chapter: 26, verse_start: 1, verse_end: 14, name: 'The Tabernacle Structure: Coverings and Curtains' },
  { chapter: 26, verse_start: 15, verse_end: 30, name: 'The Frame Structure and Assembly' },
  { chapter: 26, verse_start: 31, verse_end: 37, name: 'The Dividing Veil and Outer Curtain' },
  { chapter: 27, verse_start: 1, verse_end: 8, name: 'The Altar of Burnt Offering' },
  { chapter: 27, verse_start: 9, verse_end: 19, name: 'The Courtyard and Outer Gate' },
  { chapter: 30, verse_start: 22, verse_end: 38, name: 'The Consecration Oil and Sacred Incense' },
  { chapter: 30, verse_start: 17, verse_end: 21, name: 'The Basin for Priestly Washing' },
  { chapter: 30, verse_start: 11, verse_end: 16, name: 'The Tabernacle Census Tax' },
  { chapter: 31, verse_start: 1, verse_end: 11, name: 'Craftsmen Appointed: Bezalel and Oholiab' },
  { chapter: 28, verse_start: 1, verse_end: 43, name: 'The Priestly Garments: Holiness Visible' },
  { chapter: 29, verse_start: 1, verse_end: 46, name: 'Priestly Consecration Ceremony' },
  { chapter: 29, verse_start: 38, verse_end: 42, name: 'Daily Sacrificial Routine: Morning and Evening' },
  { chapter: 30, verse_start: 1, verse_end: 10, name: 'The Most Holy Place Entrance and Atonement' },
  { chapter: 31, verse_start: 12, verse_end: 17, name: 'Sabbath Observance and Covenant Sign' },
  { chapter: 32, verse_start: 2, verse_end: 6, name: 'Aaron\'s Golden Calf Construction' },
  { chapter: 32, verse_start: 7, verse_end: 14, name: 'God\'s Wrath and Moses\' Intercession' },
  { chapter: 32, verse_start: 15, verse_end: 24, name: 'The Tablets Broken and Covenant Rupture' },
  { chapter: 32, verse_start: 25, verse_end: 29, name: 'The Levites\' Zeal and Judicial Execution' },
  { chapter: 32, verse_start: 30, verse_end: 35, name: 'God\'s Plague and Moses\' Second Intercession' },
  { chapter: 34, verse_start: 1, verse_end: 4, name: 'The Renewed Covenant and Second Tablets' },
  { chapter: 34, verse_start: 10, verse_end: 28, name: 'God\'s Warnings and Land Promise Reiterated' },
  { chapter: 34, verse_start: 29, verse_end: 33, name: 'Moses\' Transformed Face: Glory\'s Sign' },
  { chapter: 34, verse_start: 34, verse_end: 35, name: 'Covenant Renewal Complete: Presence Restored' },
  { chapter: 35, verse_start: 1, verse_end: 3, name: 'Sabbath Rest Requirement Reaffirmed' },
  { chapter: 35, verse_start: 4, verse_end: 29, name: 'The Offering Campaign and Freewill Giving' },
  { chapter: 36, verse_start: 8, verse_end: 19, name: 'Construction of Coverings and Curtains' },
  { chapter: 37, verse_start: 1, verse_end: 9, name: 'The Ark Constructed and Furnished' },
  { chapter: 37, verse_start: 10, verse_end: 16, name: 'The Table and Bread of the Presence' },
  { chapter: 37, verse_start: 17, verse_end: 24, name: 'The Golden Lampstand Constructed' },
  { chapter: 37, verse_start: 25, verse_end: 29, name: 'The Altars and Incense Vessels' },
  { chapter: 38, verse_start: 1, verse_end: 7, name: 'The Altar of Burnt Offering' },
  { chapter: 38, verse_start: 9, verse_end: 20, name: 'The Courtyard Structure Completed' },
  { chapter: 38, verse_start: 21, verse_end: 31, name: 'Calculation of Materials Used' },
  { chapter: 39, verse_start: 1, verse_end: 31, name: 'The Priestly Garments Made' },
  { chapter: 39, verse_start: 32, verse_end: 43, name: 'Inspection and Moses\' Approval' },
  { chapter: 40, verse_start: 1, verse_end: 15, name: 'The Tabernacle Assembly: Setting Up' },
  { chapter: 40, verse_start: 16, verse_end: 33, name: 'Component Placement and Positioning' },
  { chapter: 40, verse_start: 31, verse_end: 33, name: 'Priestly Consecration and Washing' },
  { chapter: 40, verse_start: 34, verse_end: 35, name: 'The Glory of the Lord Fills the Tabernacle' },
  { chapter: 40, verse_start: 36, verse_end: 37, name: 'Divine Guidance: Cloud and Fire Pillars' }
];
