/**
 * LEVITICUS PERICOPES
 * Converted from memory-method-bible comprehensive research outlines
 * Optimized for memorization: text-driven boundaries, evocative titles
 */

export const LEVITICUS_PERICOPES = [
  { chapter: 1, verse_start: 1, verse_end: 9, name: 'The Burnt Offering from Cattle' },
  { chapter: 1, verse_start: 10, verse_end: 13, name: 'The Burnt Offering from the Flock' },
  { chapter: 1, verse_start: 14, verse_end: 17, name: 'The Burnt Offering of Birds' },
  { chapter: 2, verse_start: 1, verse_end: 3, name: 'The Grain Offering of Fine Flour' },
  { chapter: 2, verse_start: 4, verse_end: 10, name: 'The Grain Offering Prepared in Oven or Griddle' },
  { chapter: 2, verse_start: 11, verse_end: 13, name: 'General Rules for Grain Offerings' },
  { chapter: 2, verse_start: 14, verse_end: 16, name: 'The Grain Offering of Firstfruits' },
  { chapter: 3, verse_start: 1, verse_end: 5, name: 'The Peace Offering from Cattle' },
  { chapter: 3, verse_start: 6, verse_end: 16, name: 'The Peace Offering from the Flock' },
  { chapter: 4, verse_start: 1, verse_end: 12, name: 'The Purification Offering for the Anointed Priest' },
  { chapter: 4, verse_start: 13, verse_end: 21, name: 'The Purification Offering for the Whole Congregation' },
  { chapter: 4, verse_start: 22, verse_end: 26, name: 'The Purification Offering for a Leader' },
  { chapter: 4, verse_start: 27, verse_end: 35, name: 'The Purification Offering for a Common Person' },
  { chapter: 5, verse_start: 1, verse_end: 4, name: 'The Purification Offering for Sins of Omission' },
  { chapter: 5, verse_start: 5, verse_end: 13, name: 'The Purification Offering with Confession and Sliding Scale' },
  { chapter: 5, verse_start: 14, verse_end: 19, name: 'The Guilt Offering for Sacrilege' },
  { chapter: 6, verse_start: 1, verse_end: 7, name: 'The Guilt Offering for Sins Against a Neighbor' },
  { chapter: 6, verse_start: 8, verse_end: 13, name: 'The Law of the Burnt Offering (Priest\'s Duty)' },
  { chapter: 6, verse_start: 14, verse_end: 18, name: 'The Law of the Grain Offering (Priest\'s Portion)' },
  { chapter: 6, verse_start: 19, verse_end: 23, name: 'The Priest\'s Own Daily Grain Offering' },
  { chapter: 6, verse_start: 24, verse_end: 30, name: 'The Law of the Purification Offering (Priest\'s Duty)' },
  { chapter: 7, verse_start: 1, verse_end: 10, name: 'The Law of the Guilt Offering (Priest\'s Portion)' },
  { chapter: 7, verse_start: 11, verse_end: 15, name: 'The Law of the Peace Offering (Thanksgiving)' },
  { chapter: 7, verse_start: 16, verse_end: 21, name: 'The Law of the Peace Offering (Vow or Freewill)' },
  { chapter: 7, verse_start: 22, verse_end: 27, name: 'Concluding Prohibition on Fat and Blood (Reiterated)' },
  { chapter: 7, verse_start: 28, verse_end: 36, name: 'The Priest\'s Permanent Portion' },
  { chapter: 7, verse_start: 37, verse_end: 38, name: 'Concluding Colophon for Story 1' },
  { chapter: 8, verse_start: 1, verse_end: 4, name: 'The Command to Consecrate Aaron and His Sons' },
  { chapter: 8, verse_start: 5, verse_end: 9, name: 'The Consecration: Washing and Vesting Aaron' },
  { chapter: 8, verse_start: 10, verse_end: 12, name: 'The Consecration: Anointing Tabernacle and Aaron' },
  { chapter: 8, verse_start: 14, verse_end: 17, name: 'The Consecration: The Purification Offering' },
  { chapter: 8, verse_start: 18, verse_end: 21, name: 'The Consecration: The Burnt Offering' },
  { chapter: 8, verse_start: 22, verse_end: 24, name: 'The Consecration: The Ordination Offering' },
  { chapter: 8, verse_start: 25, verse_end: 30, name: 'The Consecration: Wave Offering and Final Anointing' },
  { chapter: 8, verse_start: 31, verse_end: 36, name: 'The Seven-Day Wait at the Tent' },
  { chapter: 9, verse_start: 1, verse_end: 21, name: 'The Eighth Day: Aaron\'s First Sacrifices' },
  { chapter: 9, verse_start: 22, verse_end: 24, name: 'The Divine Affirmation: Glory Appears' },
  { chapter: 10, verse_start: 1, verse_end: 3, name: 'The Crisis: Nadab and Abihu\'s Unauthorized Fire' },
  { chapter: 10, verse_start: 4, verse_end: 7, name: 'The Aftermath: Removing Bodies' },
  { chapter: 10, verse_start: 8, verse_end: 11, name: 'New Law: No Alcohol for Priests' },
  { chapter: 10, verse_start: 12, verse_end: 18, name: 'The Second Crisis: The Uneaten Offering' },
  { chapter: 10, verse_start: 19, verse_end: 20, name: 'The Resolution: Aaron\'s Justification and Approval' },
  { chapter: 11, verse_start: 1, verse_end: 8, name: 'Clean and Unclean Land Animals' },
  { chapter: 11, verse_start: 9, verse_end: 19, name: 'Clean and Unclean Water and Air Animals' },
  { chapter: 11, verse_start: 20, verse_end: 23, name: 'Unclean Insects and Swarming Things' },
  { chapter: 11, verse_start: 24, verse_end: 28, name: 'Contagion from Animal Carcasses' },
  { chapter: 11, verse_start: 29, verse_end: 38, name: 'Contagion from Swarming Things and Vessels' },
  { chapter: 11, verse_start: 39, verse_end: 47, name: 'Concluding Summary on Animal Uncleanness' },
  { chapter: 12, verse_start: 1, verse_end: 5, name: 'Impurity from Childbirth' },
  { chapter: 12, verse_start: 6, verse_end: 8, name: 'The Purification Ritual for Childbirth' },
  { chapter: 13, verse_start: 1, verse_end: 8, name: 'Diagnosing Malignant Skin Disease (Tzara\'at)' },
  { chapter: 13, verse_start: 9, verse_end: 23, name: 'Diagnosing Chronic Tzara\'at and Boils' },
  { chapter: 13, verse_start: 24, verse_end: 37, name: 'Diagnosing Burns, Scalds, and Scalp Conditions' },
  { chapter: 13, verse_start: 38, verse_end: 44, name: 'Diagnosing Benign Spots and Baldness' },
  { chapter: 13, verse_start: 45, verse_end: 46, name: 'The Conduct of the Unclean Person' },
  { chapter: 13, verse_start: 47, verse_end: 59, name: 'Diagnosing Tzara\'at in Garments' },
  { chapter: 14, verse_start: 1, verse_end: 9, name: 'The Cleansing Ritual for Tzara\'at (Day 1: The Birds)' },
  { chapter: 14, verse_start: 10, verse_end: 20, name: 'The Cleansing Ritual (Day 8: The Sacrifices)' },
  { chapter: 14, verse_start: 21, verse_end: 32, name: 'The Cleansing Ritual (Sliding Scale for the Poor)' },
  { chapter: 14, verse_start: 33, verse_end: 47, name: 'Diagnosing and Cleansing Tzara\'at in Houses' },
  { chapter: 14, verse_start: 48, verse_end: 57, name: 'The Ritual for Cleansing a House' },
  { chapter: 15, verse_start: 1, verse_end: 12, name: 'Impurity from Male Bodily Discharges (Unnatural)' },
  { chapter: 15, verse_start: 13, verse_end: 15, name: 'The Cleansing Ritual for Male Discharges' },
  { chapter: 15, verse_start: 16, verse_end: 18, name: 'Impurity from Male Bodily Discharges (Natural)' },
  { chapter: 15, verse_start: 19, verse_end: 24, name: 'Impurity from Female Bodily Discharges (Natural)' },
  { chapter: 15, verse_start: 25, verse_end: 30, name: 'Impurity from Female Bodily Discharges (Unnatural)' },
  { chapter: 15, verse_start: 31, verse_end: 33, name: 'Concluding Colophon for Story 3' },
  { chapter: 16, verse_start: 1, verse_end: 2, name: '(A) Introduction: Prohibition on Free Entry' },
  { chapter: 16, verse_start: 3, verse_end: 5, name: '(B) Priest\'s Preparation: White Linen and Animals' },
  { chapter: 16, verse_start: 6, verse_end: 10, name: '(C) The Two Goats and Lot Casting' },
  { chapter: 16, verse_start: 11, verse_end: 14, name: '(D) Purging Holy of Holies with Bull\'s Blood' },
  { chapter: 16, verse_start: 15, verse_end: 17, name: '(E) Chiastic Center: Purging with Goat\'s Blood for People' },
  { chapter: 16, verse_start: 18, verse_end: 20, name: '(D\') Purging Outer Altar' },
  { chapter: 16, verse_start: 20, verse_end: 22, name: '(C\') Sending Azazel Goat into Wilderness' },
  { chapter: 16, verse_start: 23, verse_end: 28, name: '(B\') Priest\'s Return to Normal Duties' },
  { chapter: 16, verse_start: 29, verse_end: 34, name: '(A\') Permanent Statute: Yom Kippur Established' },
  { chapter: 17, verse_start: 1, verse_end: 7, name: 'Prologue: Centralizing Sacrifice' },
  { chapter: 17, verse_start: 8, verse_end: 16, name: 'Prologue: The Sacred Nature of Blood' },
  { chapter: 18, verse_start: 1, verse_end: 5, name: 'Sexual Laws: Introduction' },
  { chapter: 18, verse_start: 6, verse_end: 18, name: 'Sexual Laws: Prohibited Family Relations' },
  { chapter: 18, verse_start: 19, verse_end: 23, name: 'Sexual Laws: Prohibited Acts and Molech' },
  { chapter: 18, verse_start: 24, verse_end: 30, name: 'Sexual Laws: Warning and Consequences' },
  { chapter: 19, verse_start: 1, verse_end: 4, name: 'The Holiness Kernel: Core Laws' },
  { chapter: 19, verse_start: 5, verse_end: 10, name: 'Laws on Ritual and Social Justice' },
  { chapter: 19, verse_start: 11, verse_end: 14, name: 'Laws on Community Ethics' },
  { chapter: 19, verse_start: 15, verse_end: 18, name: 'The Climax: Love Your Neighbor' },
  { chapter: 19, verse_start: 20, verse_end: 28, name: 'Various Laws Bound by \'I am the LORD\'' },
  { chapter: 19, verse_start: 29, verse_end: 37, name: 'Concluding Laws: Holiness Extended' },
  { chapter: 20, verse_start: 1, verse_end: 8, name: 'Penalties: Molech and Mediums' },
  { chapter: 20, verse_start: 9, verse_end: 21, name: 'Penalties: Family and Sexual Sins' },
  { chapter: 20, verse_start: 22, verse_end: 27, name: 'Conclusion: Holiness as Separation' },
  { chapter: 21, verse_start: 1, verse_end: 15, name: 'Priestly Holiness: Mourning and Marriage' },
  { chapter: 21, verse_start: 16, verse_end: 24, name: 'Priestly Holiness: Physical Blemishes' },
  { chapter: 22, verse_start: 1, verse_end: 9, name: 'Rules for Eating Holy Food: Who' },
  { chapter: 22, verse_start: 10, verse_end: 16, name: 'Rules for Eating Holy Food: Households' },
  { chapter: 22, verse_start: 17, verse_end: 25, name: 'Rules for Unblemished Sacrifices' },
  { chapter: 22, verse_start: 26, verse_end: 33, name: 'Rules for Specific Sacrifices' },
  { chapter: 23, verse_start: 1, verse_end: 8, name: 'The Liturgical Calendar: Sabbath and Passover' },
  { chapter: 23, verse_start: 9, verse_end: 22, name: 'Agricultural Feasts: Firstfruits and Weeks' },
  { chapter: 23, verse_start: 23, verse_end: 32, name: 'Fall Feasts: Trumpets and Atonement' },
  { chapter: 23, verse_start: 33, verse_end: 44, name: 'Fall Feast: Booths (Sukkot)' },
  { chapter: 24, verse_start: 1, verse_end: 9, name: 'Tabernacle Interior: Oil and Bread' },
  { chapter: 24, verse_start: 10, verse_end: 12, name: 'Narrative: Blasphemy Case Study' },
  { chapter: 24, verse_start: 13, verse_end: 23, name: 'The Law of Blasphemy and Talion' },
  { chapter: 25, verse_start: 1, verse_end: 7, name: 'The Sabbatical Year' },
  { chapter: 25, verse_start: 8, verse_end: 13, name: 'The Jubilee Proclamation' },
  { chapter: 25, verse_start: 14, verse_end: 18, name: 'Jubilee Economic Laws' },
  { chapter: 25, verse_start: 19, verse_end: 22, name: 'Sabbatical Theological Rationale' },
  { chapter: 25, verse_start: 25, verse_end: 34, name: 'Redeeming Land and Houses' },
  { chapter: 25, verse_start: 35, verse_end: 43, name: 'Redeeming Israelite Servants' },
  { chapter: 25, verse_start: 44, verse_end: 46, name: 'Foreign Slaves and Property' },
  { chapter: 25, verse_start: 47, verse_end: 55, name: 'Israelite Sold to Sojourner' },
  { chapter: 26, verse_start: 1, verse_end: 2, name: 'Epilogue: Final Warning Summary' },
  { chapter: 26, verse_start: 3, verse_end: 13, name: 'Epilogue: The Blessings' },
  { chapter: 26, verse_start: 14, verse_end: 17, name: 'Epilogue: First Wave of Curses' },
  { chapter: 26, verse_start: 18, verse_end: 26, name: 'Epilogue: Escalating Curses (Sevenfold)' },
  { chapter: 26, verse_start: 27, verse_end: 39, name: 'Epilogue: Final Wave—Exile' },
  { chapter: 26, verse_start: 40, verse_end: 46, name: 'Epilogue: Hope and Restoration' },
  { chapter: 27, verse_start: 1, verse_end: 8, name: 'The Valuation of Persons' },
  { chapter: 27, verse_start: 9, verse_end: 13, name: 'The Valuation of Animals' },
  { chapter: 27, verse_start: 14, verse_end: 15, name: 'The Valuation of Houses' },
  { chapter: 27, verse_start: 16, verse_end: 21, name: 'The Valuation of Land (Inherited)' },
  { chapter: 27, verse_start: 22, verse_end: 25, name: 'The Valuation of Land (Purchased)' },
  { chapter: 27, verse_start: 26, verse_end: 29, name: 'Irredeemable Things' },
  { chapter: 27, verse_start: 30, verse_end: 33, name: 'The Law of the Tithe' }
];
