/**
 * NUMBERS PERICOPES
 * Converted from memory-method-bible comprehensive research outlines
 * Optimized for memorization: text-driven boundaries, evocative titles
 */

export const NUMBERS_PERICOPES = [
  { chapter: 1, verse_start: 1, verse_end: 4, name: 'The Census Command' },
  { chapter: 1, verse_start: 5, verse_end: 16, name: 'Appointing the Tribal Leaders' },
  { chapter: 1, verse_start: 17, verse_end: 19, name: 'The Census Execution' },
  { chapter: 1, verse_start: 20, verse_end: 43, name: 'The Tribal Census Count' },
  { chapter: 1, verse_start: 44, verse_end: 47, name: 'The Grand Total' },
  { chapter: 1, verse_start: 48, verse_end: 54, name: 'The Role of the Levites' },
  { chapter: 2, verse_start: 1, verse_end: 2, name: 'The Command to Encamp' },
  { chapter: 2, verse_start: 3, verse_end: 31, name: 'The Camp Layout by Tribes' },
  { chapter: 2, verse_start: 32, verse_end: 34, name: 'The Final Camp Summary' },
  { chapter: 3, verse_start: 1, verse_end: 10, name: 'The Levitical Priesthood (Aaron\'s Sons)' },
  { chapter: 3, verse_start: 11, verse_end: 13, name: 'The Levites as Firstborn Substitutes' },
  { chapter: 3, verse_start: 14, verse_end: 39, name: 'The Census of the Levites' },
  { chapter: 3, verse_start: 40, verse_end: 51, name: 'The Redemption of the Firstborn' },
  { chapter: 4, verse_start: 1, verse_end: 20, name: 'The Duties of the Kohathites' },
  { chapter: 4, verse_start: 21, verse_end: 33, name: 'The Duties of Gershon and Merari' },
  { chapter: 4, verse_start: 34, verse_end: 49, name: 'The Results of the Levitical Census' },
  { chapter: 5, verse_start: 1, verse_end: 4, name: 'Laws of Camp Purity (The Unclean)' },
  { chapter: 5, verse_start: 5, verse_end: 10, name: 'Laws of Restitution' },
  { chapter: 5, verse_start: 11, verse_end: 31, name: 'The Law of Suspected Unfaithfulness' },
  { chapter: 6, verse_start: 1, verse_end: 21, name: 'The Law of the Nazirite' },
  { chapter: 6, verse_start: 22, verse_end: 27, name: 'The Priestly Blessing' },
  { chapter: 7, verse_start: 1, verse_end: 88, name: 'The Offerings of the Leaders (Days 1-12)' },
  { chapter: 8, verse_start: 1, verse_end: 4, name: 'The Tabernacle Lamps' },
  { chapter: 8, verse_start: 5, verse_end: 26, name: 'The Consecration of the Levites' },
  { chapter: 9, verse_start: 1, verse_end: 14, name: 'The Second Passover' },
  { chapter: 9, verse_start: 15, verse_end: 23, name: 'The Guiding Cloud' },
  { chapter: 10, verse_start: 1, verse_end: 10, name: 'The Two Silver Trumpets' },
  { chapter: 10, verse_start: 11, verse_end: 13, name: 'The Cloud Moves and the March Begins' },
  { chapter: 10, verse_start: 14, verse_end: 28, name: 'The Order of the March' },
  { chapter: 10, verse_start: 29, verse_end: 32, name: 'Moses and Hobab' },
  { chapter: 10, verse_start: 33, verse_end: 36, name: 'The Invocations of the Ark' },
  { chapter: 11, verse_start: 1, verse_end: 3, name: 'The Fire at Taberah' },
  { chapter: 11, verse_start: 4, verse_end: 9, name: 'The People Crave Meat' },
  { chapter: 11, verse_start: 10, verse_end: 15, name: 'Moses\' Complaint' },
  { chapter: 11, verse_start: 16, verse_end: 30, name: 'The Seventy Elders' },
  { chapter: 11, verse_start: 31, verse_end: 35, name: 'The Quail and the Plague' },
  { chapter: 12, verse_start: 1, verse_end: 16, name: 'The Rebellion of Miriam and Aaron' },
  { chapter: 13, verse_start: 1, verse_end: 16, name: 'The Twelve Spies Are Sent' },
  { chapter: 13, verse_start: 17, verse_end: 20, name: 'Moses\' Instructions to the Spies' },
  { chapter: 13, verse_start: 21, verse_end: 25, name: 'The Spies\' Journey' },
  { chapter: 13, verse_start: 26, verse_end: 29, name: 'The Spies\' Report' },
  { chapter: 13, verse_start: 31, verse_end: 33, name: 'The Negative Report Spreads' },
  { chapter: 14, verse_start: 1, verse_end: 4, name: 'The People\'s Rebellion' },
  { chapter: 14, verse_start: 5, verse_end: 9, name: 'The Leaders\' Plea' },
  { chapter: 14, verse_start: 10, verse_end: 19, name: 'The Divine Judgment and Moses\' Intercession' },
  { chapter: 14, verse_start: 20, verse_end: 35, name: 'The 40-Year Decree' },
  { chapter: 14, verse_start: 36, verse_end: 38, name: 'The Ten Spies Die' },
  { chapter: 14, verse_start: 39, verse_end: 45, name: 'The Abortive Invasion' },
  { chapter: 15, verse_start: 1, verse_end: 41, name: 'Laws for the Next Generation' },
  { chapter: 16, verse_start: 1, verse_end: 35, name: 'The Rebellion of Korah' },
  { chapter: 18, verse_start: 1, verse_end: 32, name: 'Duties of Priests and Levites' },
  { chapter: 19, verse_start: 1, verse_end: 22, name: 'The Red Heifer' },
  { chapter: 20, verse_start: 1, verse_end: 13, name: 'The Death of Miriam; Water from the Rock (Meribah)' },
  { chapter: 20, verse_start: 14, verse_end: 21, name: 'Edom Refuses Passage' },
  { chapter: 20, verse_start: 22, verse_end: 29, name: 'The Death of Aaron' },
  { chapter: 21, verse_start: 1, verse_end: 9, name: 'The Bronze Serpent' },
  { chapter: 21, verse_start: 10, verse_end: 35, name: 'Journey to Moab' },
  { chapter: 22, verse_start: 1, verse_end: 14, name: 'Balak Summons Balaam (The Balaam Pericope)' },
  { chapter: 22, verse_start: 15, verse_end: 21, name: 'Balaam Goes to Balak' },
  { chapter: 22, verse_start: 22, verse_end: 35, name: 'The Talking Donkey' },
  { chapter: 23, verse_start: 13, verse_end: 26, name: 'Balaam\'s Second Oracle' },
  { chapter: 24, verse_start: 15, verse_end: 25, name: 'Balaam\'s Final Oracles (The Star from Jacob)' },
  { chapter: 25, verse_start: 1, verse_end: 9, name: 'The Apostasy at Baal Peor' },
  { chapter: 25, verse_start: 10, verse_end: 18, name: 'The Covenant with Phinehas' },
  { chapter: 26, verse_start: 1, verse_end: 51, name: 'The Second Census' },
  { chapter: 26, verse_start: 52, verse_end: 56, name: 'Principles of Land Division' },
  { chapter: 26, verse_start: 57, verse_end: 65, name: 'Census of Levites and Thematic Climax' },
  { chapter: 27, verse_start: 1, verse_end: 11, name: 'The Case of Zelophehad\'s Daughters' },
  { chapter: 27, verse_start: 12, verse_end: 23, name: 'Joshua Appointed as Successor' },
  { chapter: 28, verse_start: 1, verse_end: 15, name: 'Laws of Offerings (Daily, Sabbath, Monthly)' },
  { chapter: 30, verse_start: 1, verse_end: 16, name: 'Laws Concerning Vows' },
  { chapter: 31, verse_start: 1, verse_end: 12, name: 'The War Against Midian' },
  { chapter: 31, verse_start: 13, verse_end: 54, name: 'The Purification of Spoils and Division of Plunder' },
  { chapter: 32, verse_start: 1, verse_end: 42, name: 'The Transjordan Tribes (Reuben and Gad)' },
  { chapter: 33, verse_start: 1, verse_end: 49, name: 'The Summary of Israel\'s Journeys' },
  { chapter: 33, verse_start: 50, verse_end: 56, name: 'Instructions for Conquering the Land' },
  { chapter: 34, verse_start: 1, verse_end: 29, name: 'The Boundaries of the Land' },
  { chapter: 35, verse_start: 1, verse_end: 34, name: 'The Cities of Refuge' },
  { chapter: 36, verse_start: 1, verse_end: 13, name: 'The Marriage of Heiresses (Bookend)' }
];
