/**
 * DEUTERONOMY PERICOPES
 * Converted from memory-method-bible comprehensive research outlines
 * Optimized for memorization: text-driven boundaries, evocative titles
 */

export const DEUTERONOMY_PERICOPES = [
  { chapter: 1, verse_start: 1, verse_end: 5, name: 'The Superscription and Authority' },
  { chapter: 1, verse_start: 6, verse_end: 8, name: 'The Command from Horeb' },
  { chapter: 1, verse_start: 9, verse_end: 18, name: 'The Appointment of Judges' },
  { chapter: 1, verse_start: 19, verse_end: 33, name: 'The Mission of the Spies' },
  { chapter: 1, verse_start: 34, verse_end: 46, name: 'The Penalty for Unbelief' },
  { chapter: 2, verse_start: 1, verse_end: 25, name: 'The Years of Wandering' },
  { chapter: 2, verse_start: 26, verse_end: 37, name: 'The Conquest of Sihon' },
  { chapter: 3, verse_start: 1, verse_end: 11, name: 'The Conquest of Og' },
  { chapter: 3, verse_start: 12, verse_end: 22, name: 'Land Distribution in Transjordan' },
  { chapter: 3, verse_start: 23, verse_end: 29, name: 'Moses\'s Plea and God\'s Refusal' },
  { chapter: 4, verse_start: 1, verse_end: 8, name: 'The Great Exhortation to Obey' },
  { chapter: 4, verse_start: 9, verse_end: 14, name: 'The Warning from Horeb Experience' },
  { chapter: 4, verse_start: 15, verse_end: 24, name: 'The Warning Against Idolatry' },
  { chapter: 4, verse_start: 25, verse_end: 31, name: 'The Prophecy of Exile and Return' },
  { chapter: 4, verse_start: 32, verse_end: 40, name: 'The Uniqueness of YHWH as Basis for Loyalty' },
  { chapter: 5, verse_start: 1, verse_end: 5, name: 'The Horeb Covenant with This Generation' },
  { chapter: 5, verse_start: 6, verse_end: 21, name: 'The Ten Commandments Recited' },
  { chapter: 5, verse_start: 22, verse_end: 33, name: 'The People\'s Fear and Request for Mediation' },
  { chapter: 6, verse_start: 1, verse_end: 3, name: 'The Purpose of the Law: Life in the Land' },
  { chapter: 6, verse_start: 4, verse_end: 9, name: 'The Shema: The Great Commandment' },
  { chapter: 4, verse_start: 41, verse_end: 43, name: 'Cities of Refuge Narrative Interlude' },
  { chapter: 4, verse_start: 44, verse_end: 49, name: 'Preamble to the Second Speech' },
  { chapter: 6, verse_start: 10, verse_end: 25, name: 'The Danger of Forgetting in Prosperity' },
  { chapter: 7, verse_start: 1, verse_end: 26, name: 'A Holy People and the Program of Conquest' },
  { chapter: 8, verse_start: 1, verse_end: 20, name: 'The Lesson of the Manna and Wilderness' },
  { chapter: 12, verse_start: 1, verse_end: 32, name: 'The Central Sanctuary' },
  { chapter: 13, verse_start: 1, verse_end: 18, name: 'The Law of the Apostate' },
  { chapter: 14, verse_start: 1, verse_end: 21, name: 'Purity Laws: Ritual and Dietary' },
  { chapter: 14, verse_start: 22, verse_end: 29, name: 'The Law of the Tithe' },
  { chapter: 15, verse_start: 1, verse_end: 18, name: 'The Sabbatical Year: Debts and Slaves' },
  { chapter: 17, verse_start: 14, verse_end: 20, name: 'The Law of the King' },
  { chapter: 18, verse_start: 1, verse_end: 22, name: 'Priests, Levites, and Prophets' },
  { chapter: 19, verse_start: 1, verse_end: 21, name: 'Cities of Refuge and Witnesses' },
  { chapter: 20, verse_start: 1, verse_end: 20, name: 'The Laws of Warfare' },
  { chapter: 21, verse_start: 1, verse_end: 23, name: 'Unsolved Murder and Family Laws' },
  { chapter: 22, verse_start: 1, verse_end: 30, name: 'Laws of Property and Sexual Morality' },
  { chapter: 23, verse_start: 1, verse_end: 25, name: 'Congregation and Camp Purity' },
  { chapter: 24, verse_start: 1, verse_end: 22, name: 'Laws of Divorce, Loans, and Justice' },
  { chapter: 25, verse_start: 1, verse_end: 19, name: 'Various Social and Civil Laws' },
  { chapter: 26, verse_start: 1, verse_end: 19, name: 'Firstfruits, Tithes, and Covenant Conclusion' },
  { chapter: 27, verse_start: 1, verse_end: 10, name: 'The Command for the Ebal Altar' },
  { chapter: 27, verse_start: 11, verse_end: 26, name: 'The Twelve Curses' },
  { chapter: 28, verse_start: 1, verse_end: 14, name: 'The Blessings for Obedience' },
  { chapter: 28, verse_start: 15, verse_end: 68, name: 'The Curses for Disobedience' },
  { chapter: 29, verse_start: 1, verse_end: 9, name: 'The Moab Covenant Preamble' },
  { chapter: 29, verse_start: 10, verse_end: 29, name: 'The Moab Covenant Ceremony' },
  { chapter: 30, verse_start: 1, verse_end: 10, name: 'The Promise of Restoration' },
  { chapter: 30, verse_start: 11, verse_end: 14, name: 'The Commandment Is Not Too Hard' },
  { chapter: 30, verse_start: 15, verse_end: 20, name: 'The Choice of Life and Death' },
  { chapter: 31, verse_start: 1, verse_end: 8, name: 'The First Commission of Joshua' },
  { chapter: 31, verse_start: 9, verse_end: 13, name: 'The Deposition of the Law' },
  { chapter: 31, verse_start: 14, verse_end: 23, name: 'The Divine Commission of Joshua and the Song' },
  { chapter: 31, verse_start: 24, verse_end: 30, name: 'The Law and Song as Witnesses' },
  { chapter: 32, verse_start: 48, verse_end: 52, name: 'God\'s Command for Moses to Ascend Nebo' },
  { chapter: 32, verse_start: 1, verse_end: 18, name: 'The Song of Moses: Indictment Phase' },
  { chapter: 32, verse_start: 19, verse_end: 43, name: 'The Song of Moses: Judgment and Restoration' },
  { chapter: 32, verse_start: 44, verse_end: 47, name: 'Narrative Conclusion to the Song' },
  { chapter: 34, verse_start: 1, verse_end: 4, name: 'The Vision from Nebo' },
  { chapter: 34, verse_start: 5, verse_end: 8, name: 'The Death and Burial of Moses' },
  { chapter: 33, verse_start: 1, verse_end: 29, name: 'The Blessing of Moses: Theophany and Tribes' },
  { chapter: 34, verse_start: 9, verse_end: 12, name: 'Joshua\'s Succession and Moses\'s Eulogy' },
  { chapter: 33, verse_start: 1, verse_end: 5, name: 'The Blessing Introduction: God\'s Majesty' },
  { chapter: 33, verse_start: 6, verse_end: 17, name: 'Tribal Blessings: Judah, Joseph, Benjamin' },
  { chapter: 33, verse_start: 18, verse_end: 29, name: 'Tribal Blessings: Levi and Others' },
  { chapter: 34, verse_start: 1, verse_end: 12, name: 'The Epilogue: Pentateuchal Conclusion' }
];
