/**
 * JUDGES PERICOPES
 * Regenerated from Memory Method Bible scenes for proper memorization granularity
 * Target: 6-12 verses per pericope, evocative titles
 */

export const JUDGES_PERICOPES = [
  { chapter: 1, verse_start: 1, verse_end: 8, name: 'Judah and Simeon\'s Partial Success' },
  { chapter: 1, verse_start: 9, verse_end: 20, name: 'Caleb\'s Inheritance and Othniel\'s Introduction' },
  { chapter: 1, verse_start: 21, verse_end: 36, name: 'The Failure of the Northern Tribes' },
  { chapter: 2, verse_start: 1, verse_end: 5, name: 'The Rebuke at Bochim' },
  { chapter: 2, verse_start: 6, verse_end: 10, name: 'The New Generation That Did Not Know the LORD' },
  { chapter: 2, verse_start: 11, verse_end: 15, name: 'The Cycle of Apostasy and Judgment' },
  { chapter: 2, verse_start: 16, verse_end: 23, name: 'The Raising of Judges and the Cycle of Failure' },
  { chapter: 3, verse_start: 1, verse_end: 6, name: 'The Nations Left as a Test' },
  { chapter: 3, verse_start: 7, verse_end: 11, name: 'The Othniel Cycle' },
  { chapter: 3, verse_start: 12, verse_end: 19, name: 'The Ehud Cycle and Eglon\'s Oppression' },
  { chapter: 3, verse_start: 20, verse_end: 29, name: 'The Assassination and Escape' },
  { chapter: 3, verse_start: 30, verse_end: 31, name: 'Shamgar\'s Fragment' },
  { chapter: 4, verse_start: 1, verse_end: 10, name: 'Deborah Summons Barak' },
  { chapter: 4, verse_start: 11, verse_end: 16, name: 'The Battle at Mount Tabor' },
  { chapter: 4, verse_start: 17, verse_end: 24, name: 'Jael and the Death of Sisera' },
  { chapter: 5, verse_start: 1, verse_end: 11, name: 'The Song of Deborah (Part 1: Praise and Summons)' },
  { chapter: 5, verse_start: 12, verse_end: 23, name: 'The Song of Deborah (Part 2: The Muster of the Tr' },
  { chapter: 5, verse_start: 24, verse_end: 31, name: 'The Song of Deborah (Part 3: Jael\'s Act and Concl' },
  { chapter: 6, verse_start: 1, verse_end: 10, name: 'Oppression by Midian; the Prophet\'s Rebuke' },
  { chapter: 6, verse_start: 11, verse_end: 24, name: 'The Call of Gideon' },
  { chapter: 6, verse_start: 25, verse_end: 32, name: 'Gideon Becomes Jerubbaal' },
  { chapter: 6, verse_start: 33, verse_end: 40, name: 'The Sign of the Fleece' },
  { chapter: 7, verse_start: 1, verse_end: 8, name: 'The Army Reduced to 300' },
  { chapter: 7, verse_start: 9, verse_end: 18, name: 'The Midianite\'s Dream' },
  { chapter: 7, verse_start: 19, verse_end: 8, name: 'The Rout of Midian and Appeasing Ephraim' },
  { chapter: 8, verse_start: 4, verse_end: 12, name: 'Gideon Pursues Zebah and Zalmunna' },
  { chapter: 8, verse_start: 13, verse_end: 21, name: 'Gideon\'s Vengeance' },
  { chapter: 8, verse_start: 22, verse_end: 28, name: 'Gideon\'s Ephod' },
  { chapter: 8, verse_start: 29, verse_end: 35, name: 'Gideon\'s Death and Israel\'s Apostasy' },
  { chapter: 9, verse_start: 1, verse_end: 6, name: 'Abimelech\'s Conspiracy at Shechem' },
  { chapter: 9, verse_start: 7, verse_end: 21, name: 'Jotham\'s Parable of the Trees' },
  { chapter: 9, verse_start: 22, verse_end: 29, name: 'The Shechem Rebellion and Gaal\'s Challenge' },
  { chapter: 9, verse_start: 30, verse_end: 49, name: 'Abimelech Defeats Gaal and Destroys Shechem' },
  { chapter: 9, verse_start: 50, verse_end: 57, name: 'The Death of Abimelech at Thebez' },
  { chapter: 10, verse_start: 1, verse_end: 5, name: 'The Minor Judges Tola and Jair' },
  { chapter: 10, verse_start: 6, verse_end: 18, name: 'Israel\'s Sin and God\'s Angry Rebuke' },
  { chapter: 11, verse_start: 1, verse_end: 11, name: 'Jephthah Recruited by Gilead' },
  { chapter: 11, verse_start: 12, verse_end: 28, name: 'Jephthah\'s Diplomatic Overture' },
  { chapter: 11, verse_start: 29, verse_end: 40, name: 'Jephthah\'s Vow and His Daughter' },
  { chapter: 12, verse_start: 1, verse_end: 7, name: 'The Shibboleth Incident' },
  { chapter: 12, verse_start: 8, verse_end: 15, name: 'The Minor Judges Ibzan, Elon, and Abdon' },
  { chapter: 13, verse_start: 1, verse_end: 14, name: 'The Angel\'s First Visit and the Nazarite Vow' },
  { chapter: 13, verse_start: 15, verse_end: 25, name: 'The Angel\'s Second Visit and Samson\'s Birth' },
  { chapter: 14, verse_start: 1, verse_end: 9, name: 'Samson\'s Philistine Wife and the Lion\'s Riddle' },
  { chapter: 14, verse_start: 10, verse_end: 20, name: 'The Wedding Feast and the Riddle\'s Betrayal' },
  { chapter: 15, verse_start: 1, verse_end: 8, name: 'The Flaming Foxes' },
  { chapter: 15, verse_start: 9, verse_end: 20, name: 'The Jawbone at Lehi' },
  { chapter: 16, verse_start: 1, verse_end: 3, name: 'Samson at Gaza' },
  { chapter: 16, verse_start: 4, verse_end: 14, name: 'Delilah\'s First Three Attempts' },
  { chapter: 16, verse_start: 15, verse_end: 22, name: 'Delilah\'s Success and Samson\'s Capture' },
  { chapter: 16, verse_start: 23, verse_end: 31, name: 'The Death of Samson' },
  { chapter: 17, verse_start: 1, verse_end: 6, name: 'Micah and His Idols' },
  { chapter: 17, verse_start: 7, verse_end: 13, name: 'Micah Hires a Levite Priest' },
  { chapter: 18, verse_start: 1, verse_end: 10, name: 'The Danite Spies and the Levite' },
  { chapter: 18, verse_start: 11, verse_end: 21, name: 'The Danites Steal Micah\'s Idols and Priest' },
  { chapter: 18, verse_start: 22, verse_end: 31, name: 'The Conquest of Laish' },
  { chapter: 19, verse_start: 1, verse_end: 15, name: 'The Levite and His Concubine Journey to Gibeah' },
  { chapter: 19, verse_start: 16, verse_end: 30, name: 'The Atrocity at Gibeah' },
  { chapter: 20, verse_start: 1, verse_end: 11, name: 'Israel Gathers at Mizpah to Judge' },
  { chapter: 20, verse_start: 12, verse_end: 28, name: 'The Civil War: Benjamin\'s First Two Victories' },
  { chapter: 20, verse_start: 29, verse_end: 48, name: 'The Ambush and Destruction of Benjamin' },
  { chapter: 21, verse_start: 1, verse_end: 14, name: 'Lament for a Lost Tribe' },
  { chapter: 21, verse_start: 15, verse_end: 25, name: 'Wives from Shiloh; The Final Verdict' }
];

export default JUDGES_PERICOPES;