/**
 * 1SAMUEL PERICOPES
 * Regenerated from Memory Method Bible scenes for proper memorization granularity
 * Target: 6-12 verses per pericope, evocative titles
 */

export const SAMUEL1_PERICOPES = [
  { chapter: 1, verse_start: 1, verse_end: 11, name: 'Hannah\'s Vexation and Vow' },
  { chapter: 1, verse_start: 12, verse_end: 18, name: 'Eli\'s Misjudgment and Hannah\'s Blessing' },
  { chapter: 1, verse_start: 19, verse_end: 28, name: 'The Birth and Dedication of Samuel' },
  { chapter: 2, verse_start: 1, verse_end: 10, name: 'Hannah\'s Prophetic Song' },
  { chapter: 2, verse_start: 11, verse_end: 21, name: 'The Contrast: Eli\'s Sons vs. Samuel' },
  { chapter: 2, verse_start: 22, verse_end: 26, name: 'Eli\'s Ineffective Rebuke and Samuel\'s Growth' },
  { chapter: 2, verse_start: 27, verse_end: 36, name: 'The Prophecy Against the House of Eli' },
  { chapter: 3, verse_start: 1, verse_end: 14, name: 'The Prophetic Call of Samuel' },
  { chapter: 3, verse_start: 15, verse_end: 18, name: 'Samuel\'s First Prophetic Task' },
  { chapter: 3, verse_start: 19, verse_end: 4, name: 'Samuel Established as Prophet' },
  { chapter: 4, verse_start: 1, verse_end: 11, name: 'The Ark Is Captured' },
  { chapter: 4, verse_start: 12, verse_end: 18, name: 'The Death of Eli' },
  { chapter: 4, verse_start: 19, verse_end: 22, name: 'The Birth of Ichabod' },
  { chapter: 5, verse_start: 1, verse_end: 5, name: 'The Ark in Ashdod: Dagon Falls' },
  { chapter: 5, verse_start: 6, verse_end: 12, name: 'The Ark Afflicts Gath and Ekron' },
  { chapter: 6, verse_start: 1, verse_end: 9, name: 'The Philistines\' Plan to Return the Ark' },
  { chapter: 6, verse_start: 10, verse_end: 18, name: 'The Ark Returns to Beth-shemesh' },
  { chapter: 6, verse_start: 19, verse_end: 7, name: 'The Ark at Kiriath-jearim' },
  { chapter: 7, verse_start: 3, verse_end: 6, name: 'Samuel\'s Call to Repentance at Mizpah' },
  { chapter: 7, verse_start: 7, verse_end: 12, name: 'The Battle of Ebenezer and Victory' },
  { chapter: 7, verse_start: 13, verse_end: 17, name: 'The Judgeship of Samuel (Summary)' },
  { chapter: 8, verse_start: 1, verse_end: 9, name: 'The Elders Demand a King' },
  { chapter: 8, verse_start: 10, verse_end: 18, name: 'Samuel Warns of the \'Manner of the King\'' },
  { chapter: 8, verse_start: 19, verse_end: 22, name: 'The People Insist on a King' },
  { chapter: 9, verse_start: 1, verse_end: 10, name: 'Saul Seeks His Father\'s Donkeys' },
  { chapter: 9, verse_start: 11, verse_end: 17, name: 'The Divine Appointment: Saul Meets Samuel' },
  { chapter: 9, verse_start: 18, verse_end: 24, name: 'Samuel Honors Saul at the Feast' },
  { chapter: 9, verse_start: 25, verse_end: 10, name: 'The Secret Anointing of Saul' },
  { chapter: 10, verse_start: 2, verse_end: 8, name: 'The Three Prophetic Signs' },
  { chapter: 10, verse_start: 9, verse_end: 13, name: 'The Signs Fulfilled' },
  { chapter: 10, verse_start: 14, verse_end: 16, name: 'Saul\'s Discreet Return Home' },
  { chapter: 10, verse_start: 17, verse_end: 24, name: 'The Public Selection by Lot at Mizpah' },
  { chapter: 10, verse_start: 25, verse_end: 27, name: 'The Kingdom Defined and Saul Dismissed' },
  { chapter: 11, verse_start: 1, verse_end: 5, name: 'The Crisis at Jabesh-gilead' },
  { chapter: 11, verse_start: 6, verse_end: 11, name: 'Saul\'s Spirit-Empowered Rescue' },
  { chapter: 11, verse_start: 12, verse_end: 15, name: 'The Kingdom Confirmed at Gilgal' },
  { chapter: 12, verse_start: 1, verse_end: 5, name: 'Samuel\'s Farewell: His Integrity' },
  { chapter: 12, verse_start: 6, verse_end: 15, name: 'Samuel\'s Rebuke and Historical Review' },
  { chapter: 12, verse_start: 16, verse_end: 19, name: 'The Sign of Thunder and Rain' },
  { chapter: 12, verse_start: 20, verse_end: 25, name: 'Samuel\'s Final Charge' },
  { chapter: 13, verse_start: 1, verse_end: 9, name: 'The Philistine Crisis and Saul\'s Impatience' },
  { chapter: 13, verse_start: 10, verse_end: 15, name: 'The First Rejection: Samuel\'s Rebuke' },
  { chapter: 13, verse_start: 15, verse_end: 23, name: 'Israel\'s Disarmed State' },
  { chapter: 14, verse_start: 1, verse_end: 7, name: 'Jonathan\'s Secret Plan of Faith' },
  { chapter: 14, verse_start: 8, verse_end: 15, name: 'Jonathan\'s Attack and the Miraculous Panic' },
  { chapter: 14, verse_start: 16, verse_end: 23, name: 'Saul\'s Confused Reaction' },
  { chapter: 14, verse_start: 24, verse_end: 30, name: 'Saul\'s Rash Oath' },
  { chapter: 14, verse_start: 31, verse_end: 35, name: 'The People Sin by Eating Blood' },
  { chapter: 14, verse_start: 36, verse_end: 42, name: 'The Lot Falls on Jonathan' },
  { chapter: 14, verse_start: 43, verse_end: 46, name: 'The People Rescue Jonathan' },
  { chapter: 14, verse_start: 47, verse_end: 52, name: 'Summary of Saul\'s Wars' },
  { chapter: 15, verse_start: 1, verse_end: 9, name: 'The Second Test: The Amalekite Command' },
  { chapter: 15, verse_start: 10, verse_end: 23, name: 'The Rebuke: \'To Obey is Better than Sacrifice\'' },
  { chapter: 15, verse_start: 24, verse_end: 31, name: 'The Torn Robe and Saul\'s Final Plea' },
  { chapter: 15, verse_start: 32, verse_end: 35, name: 'The Slaying of Agag and Samuel\'s Final Departure' },
  { chapter: 16, verse_start: 1, verse_end: 13, name: 'The Secret Anointing of David' },
  { chapter: 16, verse_start: 14, verse_end: 23, name: 'David Is Brought to Saul\'s Court' },
  { chapter: 17, verse_start: 1, verse_end: 11, name: 'The Defiance of Goliath' },
  { chapter: 17, verse_start: 12, verse_end: 24, name: 'David Arrives at the Battlefield' },
  { chapter: 17, verse_start: 25, verse_end: 30, name: 'David\'s Indignation and Eliab\'s Rebuke' },
  { chapter: 17, verse_start: 31, verse_end: 39, name: 'David Convinces Saul' },
  { chapter: 17, verse_start: 40, verse_end: 49, name: 'The Battle of David and Goliath' },
  { chapter: 17, verse_start: 50, verse_end: 54, name: 'The Rout of the Philistines' },
  { chapter: 17, verse_start: 55, verse_end: 18, name: 'The Covenant of David and Jonathan' },
  { chapter: 18, verse_start: 5, verse_end: 9, name: 'Saul\'s Jealousy Is Kindled' },
  { chapter: 18, verse_start: 10, verse_end: 16, name: 'Saul\'s First Javelin Attack' },
  { chapter: 18, verse_start: 17, verse_end: 30, name: 'The Snare of the King\'s Daughters' },
  { chapter: 19, verse_start: 1, verse_end: 7, name: 'Jonathan\'s First Intercession for David' },
  { chapter: 19, verse_start: 8, verse_end: 17, name: 'Saul\'s Second Javelin Attack and Michal\'s Decepti' },
  { chapter: 19, verse_start: 18, verse_end: 24, name: 'David Flees to Samuel at Naioth' },
  { chapter: 20, verse_start: 1, verse_end: 11, name: 'The Anxious Plan' },
  { chapter: 20, verse_start: 12, verse_end: 17, name: 'Jonathan Renews the Covenant' },
  { chapter: 20, verse_start: 18, verse_end: 29, name: 'The Test at the New Moon Feast' },
  { chapter: 20, verse_start: 30, verse_end: 34, name: 'Saul\'s Rage at Jonathan' },
  { chapter: 20, verse_start: 35, verse_end: 42, name: 'The Final Farewell' },
  { chapter: 21, verse_start: 1, verse_end: 9, name: 'David at Nob: Deception and Holy Bread' },
  { chapter: 21, verse_start: 10, verse_end: 15, name: 'David at Gath: Feigning Madness' },
  { chapter: 22, verse_start: 1, verse_end: 5, name: 'The Cave of Adullam: David Gathers Men' },
  { chapter: 22, verse_start: 6, verse_end: 10, name: 'Saul\'s Paranoia and Doeg\'s Treachery' },
  { chapter: 22, verse_start: 11, verse_end: 19, name: 'The Massacre of the Priests at Nob' },
  { chapter: 22, verse_start: 20, verse_end: 23, name: 'Abiathar Escapes to David' },
  { chapter: 23, verse_start: 1, verse_end: 6, name: 'David Saves Keilah from the Philistines' },
  { chapter: 23, verse_start: 7, verse_end: 13, name: 'David Flees Keilah' },
  { chapter: 23, verse_start: 14, verse_end: 18, name: 'Jonathan Strengthens David in Ziph' },
  { chapter: 23, verse_start: 19, verse_end: 29, name: 'The Ziphites\' Betrayal and the \'Rock of Escape\'' },
  { chapter: 24, verse_start: 1, verse_end: 12, name: 'David Spares Saul in the Cave (Part 1)' },
  { chapter: 24, verse_start: 13, verse_end: 22, name: 'Saul\'s Temporary Repentance' },
  { chapter: 25, verse_start: 1, verse_end: 12, name: 'The Death of Samuel and the Churlishness of Nabal' },
  { chapter: 25, verse_start: 13, verse_end: 22, name: 'David\'s Rash Vow and Abigail\'s Intervention' },
  { chapter: 25, verse_start: 23, verse_end: 31, name: 'Abigail\'s Wise Appeal' },
  { chapter: 25, verse_start: 32, verse_end: 38, name: 'David Repents; Nabal Dies' },
  { chapter: 25, verse_start: 39, verse_end: 44, name: 'David Marries Abigail' },
  { chapter: 26, verse_start: 1, verse_end: 12, name: 'The Ziphites\' Second Betrayal; David Spares Saul' },
  { chapter: 26, verse_start: 13, verse_end: 25, name: 'David\'s Rebuke and Saul\'s Final Farewell' },
  { chapter: 27, verse_start: 1, verse_end: 7, name: 'David Flees to Achish of Gath' },
  { chapter: 27, verse_start: 8, verse_end: 12, name: 'David\'s Deceptive Raids' },
  { chapter: 28, verse_start: 1, verse_end: 2, name: 'The Philistines Gather; David\'s Dilemma' },
  { chapter: 28, verse_start: 3, verse_end: 6, name: 'Saul\'s Despair (The Narrative Switch)' },
  { chapter: 28, verse_start: 7, verse_end: 14, name: 'Saul and the Witch of Endor' },
  { chapter: 28, verse_start: 15, verse_end: 19, name: 'The Prophecy of Saul\'s Doom' },
  { chapter: 28, verse_start: 20, verse_end: 25, name: 'Saul\'s Utter Collapse' },
  { chapter: 29, verse_start: 1, verse_end: 5, name: 'The Philistine Lords Reject David (The Narrative' },
  { chapter: 29, verse_start: 6, verse_end: 11, name: 'Achish Dismisses David' },
  { chapter: 30, verse_start: 1, verse_end: 6, name: 'The Sacking of Ziklag' },
  { chapter: 30, verse_start: 7, verse_end: 15, name: 'David Inquires of the LORD and Pursues' },
  { chapter: 30, verse_start: 16, verse_end: 20, name: 'The Defeat of the Amalekites' },
  { chapter: 30, verse_start: 21, verse_end: 25, name: 'The Law of the Spoil' },
  { chapter: 30, verse_start: 26, verse_end: 31, name: 'David Sends Spoil to Judah' },
  { chapter: 31, verse_start: 1, verse_end: 7, name: 'The Death of Saul and Jonathan on Gilboa' },
  { chapter: 31, verse_start: 8, verse_end: 13, name: 'The Desecration and Burial of Saul' }
];

export default SAMUEL1_PERICOPES;