/**
 * 2SAMUEL PERICOPES
 * Regenerated from Memory Method Bible scenes for proper memorization granularity
 * Target: 6-12 verses per pericope, evocative titles
 */

export const SAMUEL2_PERICOPES = [
  { chapter: 1, verse_start: 1, verse_end: 10, name: 'The Amalekite\'s News' },
  { chapter: 1, verse_start: 11, verse_end: 16, name: 'David Executes the Messenger' },
  { chapter: 1, verse_start: 17, verse_end: 27, name: 'The Lament for Saul and Jonathan (The Song of the' },
  { chapter: 2, verse_start: 1, verse_end: 7, name: 'David Anointed King of Judah' },
  { chapter: 2, verse_start: 8, verse_end: 11, name: 'Abner Makes Ish-bosheth King of Israel' },
  { chapter: 2, verse_start: 12, verse_end: 17, name: 'The Deadly Game at Gibeon' },
  { chapter: 2, verse_start: 18, verse_end: 23, name: 'The Death of Asahel' },
  { chapter: 2, verse_start: 24, verse_end: 32, name: 'The Truce' },
  { chapter: 3, verse_start: 1, verse_end: 5, name: 'The Waxing and Waning Houses' },
  { chapter: 3, verse_start: 6, verse_end: 11, name: 'Abner\'s Breach with Ish-bosheth' },
  { chapter: 3, verse_start: 12, verse_end: 16, name: 'Abner\'s Overture and David\'s Condition' },
  { chapter: 3, verse_start: 17, verse_end: 21, name: 'Abner Secures Israel for David' },
  { chapter: 3, verse_start: 22, verse_end: 27, name: 'The Murder of Abner' },
  { chapter: 3, verse_start: 28, verse_end: 39, name: 'David\'s Mourning and Curse' },
  { chapter: 4, verse_start: 1, verse_end: 7, name: 'The Murder of Ish-bosheth' },
  { chapter: 4, verse_start: 8, verse_end: 12, name: 'The Murderers\' Reward' },
  { chapter: 5, verse_start: 1, verse_end: 5, name: 'David Anointed King of All Israel' },
  { chapter: 5, verse_start: 6, verse_end: 10, name: 'The Conquest of Jerusalem (Zion)' },
  { chapter: 5, verse_start: 11, verse_end: 16, name: 'David\'s House and Family Established' },
  { chapter: 5, verse_start: 17, verse_end: 21, name: 'Victory at Baal-perazim' },
  { chapter: 5, verse_start: 22, verse_end: 25, name: 'Victory in the Mulberry Trees' },
  { chapter: 6, verse_start: 1, verse_end: 11, name: 'Bringing the Ark to Perez-uzzah' },
  { chapter: 6, verse_start: 12, verse_end: 19, name: 'David Brings the Ark to Jerusalem' },
  { chapter: 6, verse_start: 20, verse_end: 23, name: 'Michal Despises David' },
  { chapter: 7, verse_start: 1, verse_end: 3, name: 'David\'s Desire to Build a Temple' },
  { chapter: 7, verse_start: 4, verse_end: 17, name: 'The Davidic Covenant (Nathan\'s Oracle)' },
  { chapter: 7, verse_start: 18, verse_end: 29, name: 'David\'s Prayer of Thanksgiving' },
  { chapter: 8, verse_start: 1, verse_end: 14, name: 'David\'s Victories (Summary)' },
  { chapter: 8, verse_start: 15, verse_end: 18, name: 'David\'s Administration' },
  { chapter: 9, verse_start: 1, verse_end: 13, name: 'David\'s Kindness to Mephibosheth' },
  { chapter: 10, verse_start: 1, verse_end: 5, name: 'The Insult of the Ammonites' },
  { chapter: 10, verse_start: 6, verse_end: 14, name: 'The First Ammonite-Syrian Campaign' },
  { chapter: 10, verse_start: 15, verse_end: 19, name: 'The Second Syrian Campaign' },
  { chapter: 11, verse_start: 1, verse_end: 5, name: 'David and Bathsheba' },
  { chapter: 11, verse_start: 6, verse_end: 13, name: 'The Plot Against Uriah' },
  { chapter: 11, verse_start: 14, verse_end: 17, name: 'The Murder of Uriah' },
  { chapter: 11, verse_start: 18, verse_end: 25, name: 'Joab\'s Report' },
  { chapter: 11, verse_start: 26, verse_end: 27, name: 'David Takes Bathsheba' },
  { chapter: 12, verse_start: 1, verse_end: 6, name: 'Nathan\'s Parable' },
  { chapter: 12, verse_start: 7, verse_end: 14, name: 'Thou Art the Man' },
  { chapter: 12, verse_start: 15, verse_end: 23, name: 'The Death of the Child' },
  { chapter: 12, verse_start: 24, verse_end: 25, name: 'The Birth of Solomon' },
  { chapter: 12, verse_start: 26, verse_end: 31, name: 'The War Against Ammon Concludes' },
  { chapter: 13, verse_start: 1, verse_end: 14, name: 'Amnon\'s Lust for Tamar' },
  { chapter: 13, verse_start: 15, verse_end: 20, name: 'Amnon\'s Hatred and Tamar\'s Desolation' },
  { chapter: 13, verse_start: 21, verse_end: 22, name: 'David\'s Anger; Absalom\'s Hatred' },
  { chapter: 13, verse_start: 23, verse_end: 29, name: 'Absalom\'s Revenge' },
  { chapter: 13, verse_start: 30, verse_end: 36, name: 'The King Hears the News' },
  { chapter: 13, verse_start: 37, verse_end: 39, name: 'Absalom\'s Flight' },
  { chapter: 14, verse_start: 1, verse_end: 11, name: 'Joab\'s Parable of the Woman of Tekoah' },
  { chapter: 14, verse_start: 12, verse_end: 17, name: 'The Woman Applies the Parable' },
  { chapter: 14, verse_start: 18, verse_end: 20, name: 'David Discerns Joab\'s Hand' },
  { chapter: 14, verse_start: 21, verse_end: 24, name: 'Joab Brings Absalom to Jerusalem' },
  { chapter: 14, verse_start: 25, verse_end: 27, name: 'Absalom\'s Description' },
  { chapter: 14, verse_start: 28, verse_end: 32, name: 'Absalom Forces Joab\'s Hand' },
  { chapter: 14, verse_start: 33, verse_end: 33, name: 'The King\'s Cold Reconciliation' },
  { chapter: 15, verse_start: 1, verse_end: 6, name: 'Absalom Steals the Hearts of Israel' },
  { chapter: 15, verse_start: 7, verse_end: 12, name: 'Absalom\'s Conspiracy at Hebron' },
  { chapter: 15, verse_start: 13, verse_end: 18, name: 'David Flees Jerusalem' },
  { chapter: 15, verse_start: 19, verse_end: 23, name: 'David and Ittai the Gittite' },
  { chapter: 15, verse_start: 24, verse_end: 29, name: 'David Sends Back the Ark' },
  { chapter: 15, verse_start: 30, verse_end: 37, name: 'David and Hushai\'s Counter-Espionage' },
  { chapter: 16, verse_start: 1, verse_end: 4, name: 'Ziba\'s Deception' },
  { chapter: 16, verse_start: 5, verse_end: 14, name: 'Shimei Curses David' },
  { chapter: 16, verse_start: 15, verse_end: 19, name: 'Hushai Infiltrates Absalom\'s Court' },
  { chapter: 16, verse_start: 20, verse_end: 23, name: 'Ahithophel\'s First Counsel (Public Humiliation)' },
  { chapter: 17, verse_start: 1, verse_end: 4, name: 'Ahithophel\'s Second Counsel (Swift Pursuit)' },
  { chapter: 17, verse_start: 5, verse_end: 14, name: 'Hushai\'s Counsel (Strategic Delay)' },
  { chapter: 17, verse_start: 15, verse_end: 22, name: 'Hushai\'s Warning and the Narrow Escape' },
  { chapter: 17, verse_start: 23, verse_end: 23, name: 'Ahithophel\'s Suicide' },
  { chapter: 17, verse_start: 24, verse_end: 29, name: 'David Gathers at Mahanaim' },
  { chapter: 18, verse_start: 1, verse_end: 5, name: 'David Prepares for Battle' },
  { chapter: 18, verse_start: 6, verse_end: 17, name: 'The Battle and Death of Absalom' },
  { chapter: 18, verse_start: 18, verse_end: 18, name: 'Absalom\'s Pillar' },
  { chapter: 18, verse_start: 19, verse_end: 27, name: 'The Messengers Race to David' },
  { chapter: 18, verse_start: 28, verse_end: 33, name: 'The King Receives the News' },
  { chapter: 19, verse_start: 1, verse_end: 8, name: 'Joab Rebukes the King' },
  { chapter: 19, verse_start: 8, verse_end: 15, name: 'Israel and Judah Contend for the King' },
  { chapter: 19, verse_start: 16, verse_end: 23, name: 'Shimei Pardoned' },
  { chapter: 19, verse_start: 24, verse_end: 30, name: 'Mephibosheth\'s Plea' },
  { chapter: 19, verse_start: 31, verse_end: 40, name: 'Barzillai\'s Farewell' },
  { chapter: 19, verse_start: 41, verse_end: 43, name: 'The Breach Between Israel and Judah' },
  { chapter: 20, verse_start: 1, verse_end: 3, name: 'Sheba\'s Rebellion' },
  { chapter: 20, verse_start: 4, verse_end: 13, name: 'Joab Murders Amasa' },
  { chapter: 20, verse_start: 14, verse_end: 22, name: 'The Defeat of Sheba' },
  { chapter: 20, verse_start: 23, verse_end: 26, name: 'David\'s Cabinet Restored' },
  { chapter: 21, verse_start: 1, verse_end: 6, name: '(A) The Famine and Saul\'s Sin' },
  { chapter: 21, verse_start: 7, verse_end: 14, name: '(A) Atonement for Saul\'s Sin (Rizpah\'s Vigil)' },
  { chapter: 21, verse_start: 15, verse_end: 17, name: '(B) Battles with the Giants (I)' },
  { chapter: 21, verse_start: 18, verse_end: 22, name: '(B) Battles with the Giants (II)' },
  { chapter: 22, verse_start: 1, verse_end: 20, name: '(C) David\'s Song of Deliverance (Psalm 18) (Part' },
  { chapter: 22, verse_start: 21, verse_end: 30, name: '(C) David\'s Song (Part 2: The Covenantal Righteou' },
  { chapter: 22, verse_start: 31, verse_end: 41, name: '(C) David\'s Song (Part 3: The Warlike Power)' },
  { chapter: 22, verse_start: 42, verse_end: 51, name: '(C) David\'s Song (Part 4: The Final Victory)' },
  { chapter: 23, verse_start: 1, verse_end: 7, name: '(C\') David\'s Last Words' },
  { chapter: 23, verse_start: 8, verse_end: 17, name: '(B\') The Three Mighty Men' },
  { chapter: 23, verse_start: 18, verse_end: 39, name: '(B\') The Thirty Mighty Men' },
  { chapter: 24, verse_start: 1, verse_end: 9, name: '(A\') David\'s Sinful Census' },
  { chapter: 24, verse_start: 10, verse_end: 14, name: '(A\') The Prophet\'s Choice of Judgment' },
  { chapter: 24, verse_start: 15, verse_end: 25, name: '(A\') The Plague and the Threshing Floor' }
];

export default SAMUEL2_PERICOPES;