/**
 * 1KINGS PERICOPES
 * Regenerated from Memory Method Bible scenes for proper memorization granularity
 * Target: 6-12 verses per pericope, evocative titles
 */

export const KINGS1_PERICOPES = [
  { chapter: 1, verse_start: 1, verse_end: 10, name: 'David\'s Failing Health and the Rise of Adonijah' },
  { chapter: 1, verse_start: 11, verse_end: 31, name: 'Nathan and Bathsheba\'s Counter-Plot' },
  { chapter: 1, verse_start: 32, verse_end: 40, name: 'David\'s Charge and Solomon\'s Anointing' },
  { chapter: 1, verse_start: 41, verse_end: 53, name: 'The Conspiracy Collapses' },
  { chapter: 2, verse_start: 1, verse_end: 9, name: 'David\'s Final Charge to Solomon' },
  { chapter: 2, verse_start: 10, verse_end: 25, name: 'The Kingdom Established and Adonijah\'s Final Plot' },
  { chapter: 2, verse_start: 26, verse_end: 46, name: 'The Consolidation of the Kingdom' },
  { chapter: 3, verse_start: 1, verse_end: 4, name: 'Solomon\'s Alliance with Egypt and Worship' },
  { chapter: 2, verse_start: 10, verse_end: 12, name: 'David\'s Death and Burial' },
  { chapter: 3, verse_start: 1, verse_end: 15, name: 'The Gibeon Vision' },
  { chapter: 3, verse_start: 16, verse_end: 28, name: 'The Case of the Two Prostitutes' },
  { chapter: 4, verse_start: 1, verse_end: 19, name: 'Solomon\'s Administration and Court' },
  { chapter: 4, verse_start: 20, verse_end: 28, name: 'The Glory of the Kingdom' },
  { chapter: 4, verse_start: 29, verse_end: 34, name: 'The Wisdom of Solomon' },
  { chapter: 5, verse_start: 1, verse_end: 12, name: 'The Treaty with Hiram' },
  { chapter: 5, verse_start: 13, verse_end: 18, name: 'Solomon\'s Labor Force' },
  { chapter: 6, verse_start: 1, verse_end: 10, name: 'Building the Temple Structure' },
  { chapter: 6, verse_start: 11, verse_end: 13, name: 'The Prophetic Interruption' },
  { chapter: 6, verse_start: 14, verse_end: 38, name: 'Decorating the Temple Interior' },
  { chapter: 7, verse_start: 1, verse_end: 12, name: 'Solomon\'s Palace and Other Projects' },
  { chapter: 7, verse_start: 13, verse_end: 47, name: 'The Work of Hiram the Bronzesmith' },
  { chapter: 7, verse_start: 48, verse_end: 51, name: 'The Gold Furnishings and Final Summary' },
  { chapter: 8, verse_start: 1, verse_end: 13, name: 'Bringing the Ark into the Temple' },
  { chapter: 8, verse_start: 14, verse_end: 21, name: 'Solomon\'s First Address to the People' },
  { chapter: 8, verse_start: 22, verse_end: 30, name: 'Solomon\'s Dedicatory Prayer (Part 1: The Foundati' },
  { chapter: 8, verse_start: 31, verse_end: 53, name: 'Solomon\'s Dedicatory Prayer (Part 2: Specific Cas' },
  { chapter: 8, verse_start: 54, verse_end: 61, name: 'Solomon\'s Second Address and Blessing' },
  { chapter: 8, verse_start: 62, verse_end: 66, name: 'The Feast of Dedication' },
  { chapter: 9, verse_start: 1, verse_end: 9, name: 'The LORD\'s Second Appearance to Solomon' },
  { chapter: 9, verse_start: 10, verse_end: 28, name: 'Solomon\'s Public Works and Administration' },
  { chapter: 10, verse_start: 1, verse_end: 13, name: 'The Queen of Sheba' },
  { chapter: 10, verse_start: 14, verse_end: 29, name: 'Solomon\'s Riches and Honor' },
  { chapter: 11, verse_start: 1, verse_end: 13, name: 'Solomon\'s Apostasy' },
  { chapter: 11, verse_start: 14, verse_end: 25, name: 'The LORD Stirs Up Adversaries' },
  { chapter: 11, verse_start: 26, verse_end: 40, name: 'The Prophecy Against Jeroboam' },
  { chapter: 11, verse_start: 41, verse_end: 43, name: 'The Death of Solomon' },
  { chapter: 12, verse_start: 1, verse_end: 15, name: 'The Assembly at Shechem' },
  { chapter: 12, verse_start: 16, verse_end: 24, name: 'The Rebellion of the Ten Tribes' },
  { chapter: 12, verse_start: 25, verse_end: 33, name: 'The Sin of Jeroboam' },
  { chapter: 13, verse_start: 1, verse_end: 10, name: 'The Man of God from Judah' },
  { chapter: 13, verse_start: 11, verse_end: 32, name: 'The Old Prophet and the Lion' },
  { chapter: 13, verse_start: 33, verse_end: 34, name: 'Jeroboam\'s Unrepentance' },
  { chapter: 14, verse_start: 1, verse_end: 18, name: 'Ahijah\'s Prophecy Against Jeroboam\'s House' },
  { chapter: 14, verse_start: 19, verse_end: 31, name: 'The Regnal Summaries of Jeroboam and Rehoboam' },
  { chapter: 15, verse_start: 1, verse_end: 24, name: 'The Reigns of Abijam (Judah) and Asa (Judah)' },
  { chapter: 15, verse_start: 25, verse_end: 16, name: 'The Reigns of Nadab (Israel) and Baasha (Israel)' },
  { chapter: 16, verse_start: 8, verse_end: 28, name: 'Israel\'s Internal Collapse: Elah, Zimri, Omri' },
  { chapter: 16, verse_start: 29, verse_end: 34, name: 'The Reign of Ahab and the Curse of Jericho' },
  { chapter: 17, verse_start: 1, verse_end: 7, name: 'The Drought and the Ravens' },
  { chapter: 17, verse_start: 8, verse_end: 16, name: 'The Widow of Zarephath: The Flour and Oil' },
  { chapter: 17, verse_start: 17, verse_end: 24, name: 'The Widow of Zarephath: The Son Raised' },
  { chapter: 18, verse_start: 1, verse_end: 16, name: 'Elijah and Obadiah' },
  { chapter: 18, verse_start: 17, verse_end: 40, name: 'The Contest on Mount Carmel' },
  { chapter: 18, verse_start: 41, verse_end: 46, name: 'The Prayer for Rain' },
  { chapter: 19, verse_start: 1, verse_end: 8, name: 'Elijah\'s Flight and Despair' },
  { chapter: 19, verse_start: 9, verse_end: 18, name: 'The Theophany at Horeb' },
  { chapter: 19, verse_start: 19, verse_end: 21, name: 'The Call of Elisha' },
  { chapter: 20, verse_start: 1, verse_end: 21, name: 'Ben-hadad\'s First Siege and Ahab\'s First Victory' },
  { chapter: 20, verse_start: 22, verse_end: 34, name: 'The Battle at Aphek and Ahab\'s Second Victory' },
  { chapter: 20, verse_start: 35, verse_end: 43, name: 'The Prophet\'s Condemnation of Ahab' },
  { chapter: 21, verse_start: 1, verse_end: 4, name: 'Ahab\'s Covetousness' },
  { chapter: 21, verse_start: 5, verse_end: 16, name: 'Jezebel\'s Plot' },
  { chapter: 21, verse_start: 17, verse_end: 29, name: 'Elijah\'s Confrontation and Judgment' },
  { chapter: 22, verse_start: 1, verse_end: 12, name: 'The Royal Alliance' },
  { chapter: 22, verse_start: 13, verse_end: 28, name: 'Micaiah\'s True Prophecy' },
  { chapter: 22, verse_start: 29, verse_end: 40, name: 'The Death of Ahab' },
  { chapter: 22, verse_start: 41, verse_end: 53, name: 'Concluding Regnal Summaries' }
];

export default KINGS1_PERICOPES;