/**
 * 2KINGS PERICOPES
 * Regenerated from Memory Method Bible scenes for proper memorization granularity
 * Target: 6-12 verses per pericope, evocative titles
 */

export const KINGS2_PERICOPES = [
  { chapter: 1, verse_start: 1, verse_end: 18, name: 'Ahaziah\'s Fatal Inquiry' },
  { chapter: 2, verse_start: 1, verse_end: 12, name: 'Elijah\'s Ascension' },
  { chapter: 2, verse_start: 13, verse_end: 18, name: 'Elisha\'s Authority Established' },
  { chapter: 2, verse_start: 19, verse_end: 25, name: 'Elisha\'s First Miracles: Healing and Cursing' },
  { chapter: 3, verse_start: 1, verse_end: 27, name: 'The Campaign Against Moab' },
  { chapter: 4, verse_start: 1, verse_end: 7, name: 'The Widow\'s Oil' },
  { chapter: 4, verse_start: 8, verse_end: 17, name: 'The Shunammite Woman\'s Son: The Promise' },
  { chapter: 4, verse_start: 18, verse_end: 31, name: 'The Shunammite\'s Son: The Death' },
  { chapter: 4, verse_start: 32, verse_end: 37, name: 'The Shunammite\'s Son: The Revival' },
  { chapter: 4, verse_start: 38, verse_end: 44, name: 'Miracles at Gilgal: Death in the Pot and the Feed' },
  { chapter: 5, verse_start: 1, verse_end: 19, name: 'The Healing of Naaman' },
  { chapter: 5, verse_start: 20, verse_end: 27, name: 'Gehazi\'s Greed' },
  { chapter: 6, verse_start: 1, verse_end: 7, name: 'The Floating Axe Head' },
  { chapter: 6, verse_start: 8, verse_end: 23, name: 'Elisha and the Syrian Army' },
  { chapter: 6, verse_start: 24, verse_end: 33, name: 'The Siege of Samaria and the King\'s Vow' },
  { chapter: 7, verse_start: 1, verse_end: 11, name: 'The Prophecy and the Four Lepers' },
  { chapter: 7, verse_start: 12, verse_end: 20, name: 'The Siege Lifted and Prophecy Fulfilled' },
  { chapter: 8, verse_start: 1, verse_end: 6, name: 'The Shunammite\'s Land Restored' },
  { chapter: 8, verse_start: 7, verse_end: 15, name: 'Elisha, Hazael, and the King of Syria' },
  { chapter: 8, verse_start: 16, verse_end: 29, name: 'The Wicked Reigns of Jehoram and Ahaziah of Judah' },
  { chapter: 9, verse_start: 1, verse_end: 13, name: 'The Anointing of Jehu' },
  { chapter: 9, verse_start: 14, verse_end: 29, name: 'The Slaying of King Joram (Israel) and King Ahazi' },
  { chapter: 9, verse_start: 30, verse_end: 37, name: 'The Death of Jezebel' },
  { chapter: 10, verse_start: 1, verse_end: 11, name: 'Jehu Purges Ahab\'s House in Samaria' },
  { chapter: 10, verse_start: 12, verse_end: 28, name: 'Jehu Purges the Brethren of Ahaziah and the Worsh' },
  { chapter: 10, verse_start: 29, verse_end: 36, name: 'The Reign and Legacy of Jehu' },
  { chapter: 11, verse_start: 1, verse_end: 12, name: 'Athaliah\'s Usurpation and Joash\'s Rescue' },
  { chapter: 11, verse_start: 13, verse_end: 21, name: 'The Death of Athaliah and Jehoiada\'s Covenant' },
  { chapter: 12, verse_start: 1, verse_end: 16, name: 'Joash Repairs the Temple' },
  { chapter: 12, verse_start: 17, verse_end: 21, name: 'The Apostasy and Death of Joash' },
  { chapter: 13, verse_start: 1, verse_end: 25, name: 'Reign of Jehoahaz (Israel) and the Death of Elisha' },
  { chapter: 14, verse_start: 1, verse_end: 22, name: 'Reign of Amaziah (Judah) and War with Israel' },
  { chapter: 14, verse_start: 23, verse_end: 29, name: 'Reign of Jeroboam II (Israel) and Conclusion of t' },
  { chapter: 15, verse_start: 1, verse_end: 12, name: 'Azariah (Judah) and Zechariah (Israel): The End o' },
  { chapter: 15, verse_start: 13, verse_end: 22, name: 'Chaos in Israel: Shallum, Menahem, and the Rise o' },
  { chapter: 15, verse_start: 23, verse_end: 31, name: 'The Final Kings of Israel: Pekahiah and Pekah' },
  { chapter: 15, verse_start: 32, verse_end: 16, name: 'Jotham and Ahaz of Judah' },
  { chapter: 16, verse_start: 10, verse_end: 20, name: 'Ahaz\'s Apostasy and Death' },
  { chapter: 17, verse_start: 1, verse_end: 6, name: 'The Fall of Samaria' },
  { chapter: 17, verse_start: 7, verse_end: 17, name: 'The Theological Cause of Israel\'s Exile' },
  { chapter: 17, verse_start: 18, verse_end: 23, name: 'The Rejection of Israel and the Fate of Judah' },
  { chapter: 17, verse_start: 24, verse_end: 33, name: 'The Origin of the Samaritans' },
  { chapter: 17, verse_start: 34, verse_end: 41, name: 'The Final Summary of the Samaritan Heresy' },
  { chapter: 18, verse_start: 1, verse_end: 8, name: 'Hezekiah\'s Righteous Reign' },
  { chapter: 18, verse_start: 9, verse_end: 12, name: 'Parenthesis: The Fall of Samaria' },
  { chapter: 18, verse_start: 13, verse_end: 37, name: 'Sennacherib\'s Invasion and the Rabshakeh\'s Taunt' },
  { chapter: 19, verse_start: 1, verse_end: 7, name: 'Hezekiah and Isaiah\'s Counsel' },
  { chapter: 19, verse_start: 8, verse_end: 19, name: 'Sennacherib\'s Letter and Hezekiah\'s Prayer' },
  { chapter: 19, verse_start: 20, verse_end: 34, name: 'Isaiah\'s Prophecy Against Assyria' },
  { chapter: 19, verse_start: 35, verse_end: 37, name: 'The Deliverance from Assyria' },
  { chapter: 20, verse_start: 1, verse_end: 19, name: 'Hezekiah\'s Sickness, Recovery, and Folly' },
  { chapter: 20, verse_start: 20, verse_end: 21, name: 'The Wicked Reigns of Manasseh and Amon' },
  { chapter: 22, verse_start: 1, verse_end: 10, name: 'Josiah\'s Reign and the Discovery of the Law' },
  { chapter: 22, verse_start: 12, verse_end: 20, name: 'Huldah\'s Prophecy: Doom for Judah, Peace for Josi' },
  { chapter: 23, verse_start: 1, verse_end: 20, name: 'Josiah\'s Covenant and Reforms' },
  { chapter: 23, verse_start: 21, verse_end: 30, name: 'The Great Passover and the Death of Josiah' },
  { chapter: 23, verse_start: 31, verse_end: 37, name: 'The Reign of Jehoahaz and Jehoiakim' },
  { chapter: 24, verse_start: 1, verse_end: 17, name: 'Jehoiakim\'s Rebellion and the First Deportation (' },
  { chapter: 24, verse_start: 18, verse_end: 25, name: 'Zedekiah\'s Reign and the Final Siege' },
  { chapter: 25, verse_start: 8, verse_end: 21, name: 'The Burning of the Temple and Final Exile' },
  { chapter: 25, verse_start: 22, verse_end: 26, name: 'Gedaliah\'s Governorship and the Remnant\'s Flight' },
  { chapter: 25, verse_start: 27, verse_end: 30, name: 'Epilogue: Jehoiachin in Babylon' }
];

export default KINGS2_PERICOPES;