/**
 * 1CHRONICLES PERICOPES
 * Regenerated from Memory Method Bible scenes for proper memorization granularity
 * Target: 6-12 verses per pericope, evocative titles
 */

export const CHR1_PERICOPES = [
  { chapter: 1, verse_start: 1, verse_end: 4, name: 'From Adam to the Sons of Noah' },
  { chapter: 1, verse_start: 5, verse_end: 16, name: 'The Table of Nations: Japheth and Ham' },
  { chapter: 1, verse_start: 17, verse_end: 27, name: 'The Line of Shem to Abraham' },
  { chapter: 1, verse_start: 28, verse_end: 33, name: 'The Sons of Abraham (Ishmael and Keturah)' },
  { chapter: 1, verse_start: 34, verse_end: 54, name: 'The Line of Esau (Edom)' },
  { chapter: 2, verse_start: 1, verse_end: 17, name: 'The Sons of Israel (Judah)' },
  { chapter: 2, verse_start: 18, verse_end: 24, name: 'The Descendants of Caleb' },
  { chapter: 2, verse_start: 25, verse_end: 41, name: 'The Descendants of Jerahmeel' },
  { chapter: 2, verse_start: 42, verse_end: 55, name: 'The Remaining Lines of Judah and Caleb' },
  { chapter: 3, verse_start: 1, verse_end: 9, name: 'The Royal Line of David' },
  { chapter: 3, verse_start: 10, verse_end: 24, name: 'The Kings of Judah After David' },
  { chapter: 4, verse_start: 1, verse_end: 23, name: 'The Descendants of Judah (Revisited) and Simeon' },
  { chapter: 4, verse_start: 24, verse_end: 43, name: 'The Tribe of Simeon' },
  { chapter: 5, verse_start: 1, verse_end: 26, name: 'The Transjordan Tribes (Reuben, Gad, Manasseh)' },
  { chapter: 6, verse_start: 1, verse_end: 15, name: 'The Priestly Line of Levi' },
  { chapter: 6, verse_start: 16, verse_end: 53, name: 'The Levitical Musicians' },
  { chapter: 6, verse_start: 54, verse_end: 81, name: 'The Levitical Cities' },
  { chapter: 7, verse_start: 1, verse_end: 29, name: 'The Northern Tribes (Issachar, Benjamin, Naphtali' },
  { chapter: 7, verse_start: 30, verse_end: 40, name: 'The Tribe of Asher' },
  { chapter: 8, verse_start: 1, verse_end: 40, name: 'The Line of Benjamin and Saul' },
  { chapter: 9, verse_start: 1, verse_end: 9, name: 'The Dwellers in Jerusalem (The Remnant)' },
  { chapter: 9, verse_start: 10, verse_end: 13, name: 'The Priests in Jerusalem' },
  { chapter: 9, verse_start: 14, verse_end: 34, name: 'The Levites and Gatekeepers in Jerusalem' },
  { chapter: 9, verse_start: 35, verse_end: 44, name: 'The Family of Saul (Final Hinge)' },
  { chapter: 10, verse_start: 1, verse_end: 14, name: 'The Fall of Saul\'s House' },
  { chapter: 11, verse_start: 1, verse_end: 9, name: 'David Anointed King Over All Israel' },
  { chapter: 11, verse_start: 10, verse_end: 47, name: 'David\'s Mighty Men (The Three and the Thirty)' },
  { chapter: 12, verse_start: 1, verse_end: 40, name: 'The Armies That Came to David at Ziklag and Hebron' },
  { chapter: 13, verse_start: 1, verse_end: 14, name: 'The First Attempt to Move the Ark (Uzza\'s Death)' },
  { chapter: 14, verse_start: 1, verse_end: 17, name: 'God Blesses David in Jerusalem' },
  { chapter: 15, verse_start: 1, verse_end: 24, name: 'The Sacred Preparation to Move the Ark' },
  { chapter: 15, verse_start: 25, verse_end: 16, name: 'The Ark is Brought to Jerusalem' },
  { chapter: 16, verse_start: 7, verse_end: 36, name: 'David\'s Psalm of Thanksgiving' },
  { chapter: 16, verse_start: 37, verse_end: 43, name: 'The Concluding Worship and Celebration' },
  { chapter: 17, verse_start: 1, verse_end: 15, name: 'The Davidic Covenant' },
  { chapter: 17, verse_start: 16, verse_end: 27, name: 'David\'s Prayer of Response' },
  { chapter: 18, verse_start: 1, verse_end: 17, name: 'David\'s Victories Summarized' },
  { chapter: 19, verse_start: 1, verse_end: 19, name: 'The War with Ammon and Syria' },
  { chapter: 20, verse_start: 1, verse_end: 8, name: 'The End of the Ammonite War and Battles with Gian' },
  { chapter: 21, verse_start: 1, verse_end: 17, name: 'David\'s Sinful Census and the Plague' },
  { chapter: 21, verse_start: 18, verse_end: 22, name: 'The Altar at Ornan\'s Threshing Floor' },
  { chapter: 22, verse_start: 2, verse_end: 19, name: 'David\'s First Charge to Solomon and the Princes' },
  { chapter: 23, verse_start: 1, verse_end: 13, name: 'Solomon Made King; Levites Numbered and Grouped' },
  { chapter: 23, verse_start: 14, verse_end: 23, name: 'The Other Levitical Families' },
  { chapter: 23, verse_start: 24, verse_end: 32, name: 'The Office and Duties of the Levites' },
  { chapter: 24, verse_start: 1, verse_end: 19, name: 'The Twenty-Four Courses of the Priests' },
  { chapter: 24, verse_start: 20, verse_end: 31, name: 'The Remaining Levitical Leaders' },
  { chapter: 25, verse_start: 1, verse_end: 31, name: 'The Keepers of the Song (Musicians)' },
  { chapter: 26, verse_start: 1, verse_end: 19, name: 'The Gatekeepers (Porters)' },
  { chapter: 26, verse_start: 20, verse_end: 32, name: 'The Treasurers and Officers' },
  { chapter: 27, verse_start: 1, verse_end: 34, name: 'The Military and Civil Captains' },
  { chapter: 28, verse_start: 1, verse_end: 10, name: 'The Final Assembly: David\'s Public Charge' },
  { chapter: 28, verse_start: 11, verse_end: 21, name: 'The Pattern of the Temple Delivered' },
  { chapter: 29, verse_start: 1, verse_end: 9, name: 'The Freewill Offerings for the Temple' },
  { chapter: 29, verse_start: 10, verse_end: 20, name: 'David\'s Final Prayer and Blessing' },
  { chapter: 29, verse_start: 21, verse_end: 30, name: 'Solomon Enthroned; David\'s Reign and Death' }
];

export default CHR1_PERICOPES;