/**
 * 2CHRONICLES PERICOPES
 * Regenerated from Memory Method Bible scenes for proper memorization granularity
 * Target: 6-12 verses per pericope, evocative titles
 */

export const CHR2_PERICOPES = [
  { chapter: 1, verse_start: 1, verse_end: 6, name: 'Solomon\'s Sacrifice and Divine Mandate' },
  { chapter: 1, verse_start: 7, verse_end: 10, name: 'God\'s Offer and Solomon\'s Request' },
  { chapter: 1, verse_start: 11, verse_end: 13, name: 'The Divine Answer and Blessing' },
  { chapter: 1, verse_start: 14, verse_end: 17, name: 'Summary of Solomon\'s Wealth' },
  { chapter: 2, verse_start: 1, verse_end: 10, name: 'Solomon\'s Command to Hiram' },
  { chapter: 2, verse_start: 11, verse_end: 16, name: 'Hiram\'s Reply and Agreement' },
  { chapter: 2, verse_start: 17, verse_end: 18, name: 'The Labor Force Assembled' },
  { chapter: 3, verse_start: 1, verse_end: 7, name: 'The Temple Construction Begins' },
  { chapter: 3, verse_start: 8, verse_end: 14, name: 'The Most Holy Place and the Cherubim' },
  { chapter: 3, verse_start: 15, verse_end: 17, name: 'The Two Pillars: Jachin and Boaz' },
  { chapter: 4, verse_start: 1, verse_end: 6, name: 'The Altar, Sea, and Lavers' },
  { chapter: 4, verse_start: 7, verse_end: 10, name: 'The Golden Furnishings of the Holy Place' },
  { chapter: 4, verse_start: 11, verse_end: 5, name: 'The Work of Hiram Completed' },
  { chapter: 5, verse_start: 2, verse_end: 10, name: 'The Ark Brought to the Temple' },
  { chapter: 5, verse_start: 11, verse_end: 14, name: 'The Glory of the LORD Fills the Temple' },
  { chapter: 6, verse_start: 1, verse_end: 11, name: 'Solomon\'s Address to the People' },
  { chapter: 6, verse_start: 12, verse_end: 21, name: 'Solomon\'s Dedication Prayer: The Preamble' },
  { chapter: 6, verse_start: 22, verse_end: 25, name: 'The Prayer: For Oaths and Defeat' },
  { chapter: 6, verse_start: 26, verse_end: 31, name: 'The Prayer: For Drought and Famine' },
  { chapter: 6, verse_start: 32, verse_end: 35, name: 'The Prayer: For Foreigners and in War' },
  { chapter: 6, verse_start: 36, verse_end: 39, name: 'The Prayer: For Sin and Captivity' },
  { chapter: 6, verse_start: 40, verse_end: 42, name: 'The Prayer\'s Conclusion' },
  { chapter: 7, verse_start: 1, verse_end: 3, name: 'Fire from Heaven: The Divine Acceptance' },
  { chapter: 7, verse_start: 4, verse_end: 10, name: 'The Great Feast of Dedication' },
  { chapter: 7, verse_start: 11, verse_end: 22, name: 'God\'s Second Appearance to Solomon' },
  { chapter: 8, verse_start: 1, verse_end: 11, name: 'Solomon\'s Other Building Projects' },
  { chapter: 8, verse_start: 12, verse_end: 16, name: 'Solomon\'s Religious Organization' },
  { chapter: 8, verse_start: 17, verse_end: 18, name: 'Solomon\'s Naval Commerce' },
  { chapter: 9, verse_start: 1, verse_end: 9, name: 'The Visit of the Queen of Sheba' },
  { chapter: 9, verse_start: 10, verse_end: 28, name: 'Summary of Solomon\'s Riches' },
  { chapter: 9, verse_start: 29, verse_end: 31, name: 'The Death of Solomon' },
  { chapter: 10, verse_start: 1, verse_end: 5, name: 'The People\'s Demand' },
  { chapter: 10, verse_start: 6, verse_end: 11, name: 'The King\'s Fateful Counsel' },
  { chapter: 10, verse_start: 12, verse_end: 19, name: 'The Kingdom Is Torn' },
  { chapter: 11, verse_start: 1, verse_end: 4, name: 'Shemaiah Forbids Civil War' },
  { chapter: 11, verse_start: 5, verse_end: 23, name: 'Rehoboam\'s Fortifications and Family' },
  { chapter: 12, verse_start: 1, verse_end: 4, name: 'The Apostasy and Shishak\'s Invasion' },
  { chapter: 12, verse_start: 5, verse_end: 12, name: 'Repentance and Deliverance' },
  { chapter: 12, verse_start: 13, verse_end: 16, name: 'The Reign and Death of Rehoboam' },
  { chapter: 13, verse_start: 1, verse_end: 12, name: 'The Reign of Abijah and War with Jeroboam' },
  { chapter: 13, verse_start: 13, verse_end: 22, name: 'Divine Victory for Abijah' },
  { chapter: 14, verse_start: 1, verse_end: 7, name: 'Asa\'s Pious Accession' },
  { chapter: 14, verse_start: 8, verse_end: 15, name: 'Asa\'s Victory over Zerah the Ethiopian' },
  { chapter: 15, verse_start: 1, verse_end: 7, name: 'The Prophecy of Azariah' },
  { chapter: 15, verse_start: 8, verse_end: 19, name: 'Asa\'s Great Reform and Covenant' },
  { chapter: 16, verse_start: 1, verse_end: 11, name: 'Asa\'s Failure, Rebuke, and Disease' },
  { chapter: 16, verse_start: 12, verse_end: 14, name: 'The Death of Asa' },
  { chapter: 17, verse_start: 1, verse_end: 6, name: 'Jehoshaphat\'s Pious Accession and First Reforms' },
  { chapter: 17, verse_start: 7, verse_end: 11, name: 'The Teaching Levites' },
  { chapter: 17, verse_start: 12, verse_end: 19, name: 'Summary of Jehoshaphat\'s Military Strength' },
  { chapter: 18, verse_start: 1, verse_end: 3, name: 'The Alliance with Ahab' },
  { chapter: 18, verse_start: 4, verse_end: 11, name: 'The Lying Prophets' },
  { chapter: 18, verse_start: 12, verse_end: 27, name: 'Micaiah\'s True Prophecy' },
  { chapter: 18, verse_start: 28, verse_end: 34, name: 'The Battle at Ramoth-gilead and Ahab\'s Death' },
  { chapter: 19, verse_start: 1, verse_end: 3, name: 'The Rebuke of Jehu the Seer' },
  { chapter: 19, verse_start: 4, verse_end: 11, name: 'Jehoshaphat\'s Judicial Reforms' },
  { chapter: 20, verse_start: 1, verse_end: 4, name: 'The Great Invasion' },
  { chapter: 20, verse_start: 5, verse_end: 13, name: 'Jehoshaphat\'s National Prayer' },
  { chapter: 20, verse_start: 14, verse_end: 19, name: 'The Prophecy of Jahaziel' },
  { chapter: 20, verse_start: 20, verse_end: 25, name: 'The Miraculous Victory' },
  { chapter: 20, verse_start: 26, verse_end: 30, name: 'The Return to Jerusalem' },
  { chapter: 20, verse_start: 31, verse_end: 37, name: 'The Reign and Death of Jehoshaphat' },
  { chapter: 21, verse_start: 1, verse_end: 7, name: 'The Wicked Reign of Jehoram' },
  { chapter: 21, verse_start: 8, verse_end: 20, name: 'Elijah\'s Prophecy and Jehoram\'s Death' },
  { chapter: 22, verse_start: 1, verse_end: 6, name: 'Ahaziah and the Counsel of Athaliah' },
  { chapter: 22, verse_start: 7, verse_end: 9, name: 'The Purge of Jehu' },
  { chapter: 22, verse_start: 10, verse_end: 12, name: 'Athaliah\'s Usurpation and Joash\'s Rescue' },
  { chapter: 23, verse_start: 1, verse_end: 7, name: 'Jehoiada\'s Coup: The Plan' },
  { chapter: 23, verse_start: 8, verse_end: 11, name: 'The Coronation of Joash' },
  { chapter: 23, verse_start: 12, verse_end: 15, name: 'The Execution of Athaliah' },
  { chapter: 23, verse_start: 16, verse_end: 21, name: 'Jehoiada\'s Covenant and Reforms' },
  { chapter: 24, verse_start: 1, verse_end: 14, name: 'Joash\'s Temple Repair' },
  { chapter: 24, verse_start: 15, verse_end: 22, name: 'Joash\'s Apostasy and the Stoning of Zechariah' },
  { chapter: 24, verse_start: 23, verse_end: 27, name: 'The Judgment and Death of Joash' },
  { chapter: 25, verse_start: 1, verse_end: 13, name: 'The Reign of Amaziah and Victory over Edom' },
  { chapter: 25, verse_start: 14, verse_end: 16, name: 'Amaziah\'s Apostasy and Rebuke' },
  { chapter: 25, verse_start: 17, verse_end: 28, name: 'Amaziah\'s Defeat and Death' },
  { chapter: 26, verse_start: 1, verse_end: 15, name: 'Uzziah\'s Pious Reign and Prosperity' },
  { chapter: 26, verse_start: 16, verse_end: 23, name: 'Uzziah\'s Pride, Transgression, and Leprosy' },
  { chapter: 27, verse_start: 1, verse_end: 9, name: 'The Reign of Jotham' },
  { chapter: 28, verse_start: 1, verse_end: 8, name: 'The Wicked Reign of Ahaz' },
  { chapter: 28, verse_start: 9, verse_end: 15, name: 'The Prophecy of Oded' },
  { chapter: 28, verse_start: 16, verse_end: 27, name: 'Ahaz\'s Continued Apostasy and Death' },
  { chapter: 29, verse_start: 1, verse_end: 11, name: 'Hezekiah\'s Accession and Charge to the Levites' },
  { chapter: 29, verse_start: 12, verse_end: 19, name: 'The Levites Consecrate Themselves and the Temple' },
  { chapter: 29, verse_start: 20, verse_end: 26, name: 'The National Atonement Sacrifice' },
  { chapter: 29, verse_start: 27, verse_end: 30, name: 'The Joyful Burnt Offering' },
  { chapter: 29, verse_start: 31, verse_end: 36, name: 'The People\'s Offerings' },
  { chapter: 30, verse_start: 1, verse_end: 12, name: 'The Proclamation of the Great Passover' },
  { chapter: 30, verse_start: 13, verse_end: 20, name: 'The Celebration of the Passover' },
  { chapter: 30, verse_start: 21, verse_end: 27, name: 'The Joyful Second Week' },
  { chapter: 31, verse_start: 1, verse_end: 1, name: 'The Destruction of Idols' },
  { chapter: 31, verse_start: 2, verse_end: 10, name: 'The Reorganization of Priests and Tithes' },
  { chapter: 31, verse_start: 11, verse_end: 21, name: 'The Administration of the Tithes' },
  { chapter: 32, verse_start: 1, verse_end: 8, name: 'The Assyrian Crisis: Sennacherib\'s Threat' },
  { chapter: 32, verse_start: 9, verse_end: 19, name: 'Rabshakeh\'s Blasphemous Taunts' },
  { chapter: 32, verse_start: 20, verse_end: 23, name: 'The Miraculous Deliverance' },
  { chapter: 32, verse_start: 24, verse_end: 26, name: 'Hezekiah\'s Sickness, Pride, and Repentance' },
  { chapter: 32, verse_start: 27, verse_end: 33, name: 'The Babylonian Envoys and Hezekiah\'s Death' },
  { chapter: 33, verse_start: 1, verse_end: 9, name: 'The Great Sin of Manasseh' },
  { chapter: 33, verse_start: 10, verse_end: 17, name: 'Manasseh\'s Repentance and Restoration' },
  { chapter: 33, verse_start: 18, verse_end: 25, name: 'The Reign of Amon and Death of Manasseh' },
  { chapter: 34, verse_start: 1, verse_end: 7, name: 'Josiah\'s Early Piety and Reforms' },
  { chapter: 34, verse_start: 8, verse_end: 18, name: 'The Temple Repair and Discovery of the Law' },
  { chapter: 34, verse_start: 19, verse_end: 28, name: 'Josiah\'s Reaction and Huldah\'s Prophecy' },
  { chapter: 34, verse_start: 29, verse_end: 33, name: 'The Covenant Renewed' },
  { chapter: 35, verse_start: 1, verse_end: 11, name: 'The Great Passover: Preparations' },
  { chapter: 35, verse_start: 12, verse_end: 19, name: 'The Passover: The Offering' },
  { chapter: 35, verse_start: 20, verse_end: 27, name: 'The Tragic Death of Josiah' },
  { chapter: 36, verse_start: 1, verse_end: 4, name: 'The Reign and Deposing of Jehoahaz' },
  { chapter: 36, verse_start: 5, verse_end: 8, name: 'The Reign and Fall of Jehoiakim' },
  { chapter: 36, verse_start: 9, verse_end: 10, name: 'The Reign and Fall of Jehoiachin' },
  { chapter: 36, verse_start: 11, verse_end: 16, name: 'The Reign of Zedekiah and the Final Apostasy' },
  { chapter: 36, verse_start: 17, verse_end: 21, name: 'The Destruction of Jerusalem' },
  { chapter: 36, verse_start: 22, verse_end: 23, name: 'The Edict of Cyrus' }
];

export default CHR2_PERICOPES;