export const HOSEA_PERICOPES = [
  { chapter: 1, verse_start: 1, verse_end: 9, name: 'Hosea Marries Gomer; Three Symbolic Children' },
  { chapter: 1, verse_start: 10, verse_end: 11, name: 'Yet the Number of Israel\'s Children Shall Be Countless' },
  { chapter: 2, verse_start: 1, verse_end: 13, name: 'Contend with Your Mother; Unfaithful Wife' },
  { chapter: 2, verse_start: 14, verse_end: 23, name: 'I Will Betroth You Forever; New Covenant' },
  { chapter: 3, verse_start: 1, verse_end: 5, name: 'Go Love a Woman; Redemption and Restoration' },
  { chapter: 4, verse_start: 1, verse_end: 11, name: 'My People Destroyed for Lack of Knowledge' },
  { chapter: 4, verse_start: 12, verse_end: 19, name: 'The Spirit of Whoredom Leads Them Astray' },
  { chapter: 5, verse_start: 1, verse_end: 7, name: 'Hear This, O Priests; You Have Become a Snare' },
  { chapter: 5, verse_start: 8, verse_end: 15, name: 'Sound the Alarm in Gibeah; Ephraim\'s Trouble' },
  { chapter: 6, verse_start: 1, verse_end: 11, name: 'Come, Let Us Return to the Lord; Morning Mercy' },
  { chapter: 7, verse_start: 1, verse_end: 7, name: 'I Heal Israel but Their Evil is Revealed' },
  { chapter: 7, verse_start: 8, verse_end: 16, name: 'Ephraim Mixes with the Nations; No God' },
  { chapter: 8, verse_start: 1, verse_end: 7, name: 'Set the Trumpet to Your Lips; Reap the Whirlwind' },
  { chapter: 8, verse_start: 8, verse_end: 14, name: 'Israel Forgot Their Maker; They Built Palaces' },
  { chapter: 9, verse_start: 1, verse_end: 9, name: 'Rejoice Not; They Shall Go Into Captivity' },
  { chapter: 9, verse_start: 10, verse_end: 17, name: 'Ephraim\'s Glory Takes Flight; A Wanderer' },
  { chapter: 10, verse_start: 1, verse_end: 8, name: 'Israel Is a Luxuriant Vine; Destroy the Altars' },
  { chapter: 10, verse_start: 9, verse_end: 15, name: 'You Have Sinned Since Gibeah; Divine Wrath' },
  { chapter: 11, verse_start: 1, verse_end: 7, name: 'When Israel Was a Child; Fatherly Love' },
  { chapter: 11, verse_start: 8, verse_end: 12, name: 'How Can I Give You Up, O Ephraim?' },
  { chapter: 12, verse_start: 1, verse_end: 6, name: 'Ephraim Feeds on Wind; Jacob\'s Struggle' },
  { chapter: 12, verse_start: 7, verse_end: 14, name: 'Return to Your God; Keep Steadfast Love' },
  { chapter: 13, verse_start: 1, verse_end: 8, name: 'Ephraim\'s Glory Fades; God\'s Wrath Burned' },
  { chapter: 13, verse_start: 9, verse_end: 16, name: 'Destruction Comes; No Compassion for Rebellion' },
  { chapter: 14, verse_start: 1, verse_end: 9, name: 'Return to the Lord; Healing and Love' },
];

export default HOSEA_PERICOPES;
