export const REVELATION_PERICOPES = [
  { chapter: 1, verse_start: 1, verse_end: 8, name: 'The Revelation of Jesus Christ' },
  { chapter: 1, verse_start: 9, verse_end: 20, name: 'Like a Son of Man' },
  { chapter: 2, verse_start: 1, verse_end: 7, name: 'To Ephesus' },
  { chapter: 2, verse_start: 8, verse_end: 11, name: 'To Smyrna' },
  { chapter: 2, verse_start: 12, verse_end: 17, name: 'To Pergamum' },
  { chapter: 2, verse_start: 18, verse_end: 29, name: 'To Thyatira' },
  { chapter: 3, verse_start: 1, verse_end: 6, name: 'To Sardis' },
  { chapter: 3, verse_start: 7, verse_end: 13, name: 'To Philadelphia' },
  { chapter: 3, verse_start: 14, verse_end: 22, name: 'To Laodicea' },
  { chapter: 4, verse_start: 1, verse_end: 11, name: 'The Throne in Heaven' },
  { chapter: 5, verse_start: 1, verse_end: 14, name: 'The Lamb Who Was Slain' },
  { chapter: 6, verse_start: 1, verse_end: 17, name: 'The Six Seals' },
  { chapter: 7, verse_start: 1, verse_end: 17, name: 'The Sealed and the Multitude' },
  { chapter: 8, verse_start: 1, verse_end: 13, name: 'The Seventh Seal and Trumpets' },
  { chapter: 9, verse_start: 1, verse_end: 21, name: 'The Fifth and Sixth Trumpets' },
  { chapter: 10, verse_start: 1, verse_end: 11, name: 'The Angel with the Little Scroll' },
  { chapter: 11, verse_start: 1, verse_end: 14, name: 'The Two Witnesses' },
  { chapter: 11, verse_start: 15, verse_end: 19, name: 'The Seventh Trumpet' },
  { chapter: 12, verse_start: 1, verse_end: 17, name: 'The Woman and the Dragon' },
  { chapter: 13, verse_start: 1, verse_end: 18, name: 'The Two Beasts' },
  { chapter: 14, verse_start: 1, verse_end: 20, name: 'The Lamb and the 144000' },
  { chapter: 15, verse_start: 1, verse_end: 8, name: 'The Seven Angels with Seven Plagues' },
  { chapter: 16, verse_start: 1, verse_end: 21, name: 'The Seven Bowls of Wrath' },
  { chapter: 17, verse_start: 1, verse_end: 18, name: 'The Great Prostitute' },
  { chapter: 18, verse_start: 1, verse_end: 24, name: 'Fallen Is Babylon' },
  { chapter: 19, verse_start: 1, verse_end: 10, name: 'Hallelujah!' },
  { chapter: 19, verse_start: 11, verse_end: 21, name: 'The Rider on the White Horse' },
  { chapter: 20, verse_start: 1, verse_end: 15, name: 'The Thousand Years' },
  { chapter: 21, verse_start: 1, verse_end: 8, name: 'A New Heaven and New Earth' },
  { chapter: 21, verse_start: 9, verse_end: 27, name: 'The New Jerusalem' },
  { chapter: 22, verse_start: 1, verse_end: 5, name: 'The River of Life' },
  { chapter: 22, verse_start: 6, verse_end: 21, name: 'Come Lord Jesus' },
];
